### ISSUE TITLE
DisplayObject extern implementing Dynamic leads to runtime errors on Flash

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#1065]
This code should clearly fail at compile-time (which it does in pure Haxe with `flash.display.Sprite has no field foo`), but in OpenFL it compiles fine and crashes _at runtime_:

```haxe
package;

import flash.display.Sprite;

class Main extends Sprite  {
	public function new() {
		super();
		new Sprite().foo();
	}
}
```

```
ReferenceError: Error #1069: Property foo not found on flash.display.Sprite and there is no default value.
	at Main()
	at DocumentClass()
	at Type$/createInstance()
	at ApplicationMain$/start()
	at ApplicationMain$/init()
	at lime.app::Event_Void_Void/dispatch()
	at lime.app::Preloader/start()
	at openfl.display::Preloader/display_onComplete()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at NMEPreloader/onLoaded()
	at openfl.display::Preloader/start()
	at lime.app::Preloader/current_onEnter()
```

This is caused by OpenFL's custom `DisplayObject` extern, [which has `implements Dynamic` on Flash](https://github.com/openfl/openfl/blob/6a92f919d52561cc4994b4bd8cc66773a690e314/extern/flash/display/DisplayObject.hx#L12).

@jgranick What's the reasoning behind that? This seems like a bad idea.

**Comment by MSGhero** [comment]
In as3, not haxe, either Sprite or Movieclip is implemented that way. Maybe all the way down to DisplayObj idk. I assume haxe throws the error, while it's perfectly acceptable once it becomes a swf because that compiles in as3 iirc.

**Comment by Gama11** [comment]
That's a Flash runtime error, Haxe has nothing to do with that.

Haxe has `implements Dynamic` in its `MovieClip` extern: https://github.com/HaxeFoundation/haxe/blob/development/std/flash/display/MovieClip.hx#L3 - I don't think it's correct for `DisplayObject`.

**Comment by MSGhero** [comment]
Sorry, the error you posted is a flash runtime error, and that would happen as3 or not. What I meant was your haxe compile error would not occur in as3 unless that behavior is only available for MovieClips.

When this was added, Joshua said it was to copy the flash behavior of using `sprite.getChildByName("kid")` or just `sprite.kid`, which I guess should be in DOContainer over DO. I don't remember why it's here specifically.

**Comment by ibilon** [comment]
I remember seeing a lot of discussion about this `implements Dynamic` on slack,
was there a conclusion reached? @Gama11 @jgranick

**Comment by Gama11** [comment]
I don't think so.

@jcward and @ianharrigan also ran in to this problem.

**Comment by Gama11** [comment]
I think @jcward was looking into some macro solution?

If that doesn't work, there should probably be a define to configure this. Personally, I think that define should be used to _opt-in_ - the negative impact this has on users that _don't_ need this behavior (random runtime errors!) outweighs the few users who actually do need it. I think others would agree.

**Comment by ibilon** [comment]
Agree, IIRC this was for swf and movie clip access?

For me, considering the issues that makes, it should be reversed.
Then a plan can be made for the use case requiring it.

If that's why I think it's for then swf-lite can definitely use some macro and swf can still fail at runtime,
so no need for implementing Dynamic.

**Comment by ianharrigan** [comment]
I agree with all of the above, opt-in makes more sense to me also. It sort of feels like throwing out the baby with the bath water here. The fact that it hides errors, or at least moves them to runtime completely removed my confidence in compiling code when openfl is involved. Even if it is on by default (which personally i think is the wrong move) then someway to turn it off so i can correctly compile my codebase is paramount. This has caught me on at least 3 seperate occasions now (and all i was doing was refactoring). To the point now that i no longer use the openfl project of my code as my "go to" project as i simply cant trust the compilation process any more.

**Comment by ibilon** [comment]
I tried modifying
```haxe
extern class DisplayObject extends EventDispatcher implements IBitmapDrawable implements #if flash Dynamic #else Dynamic<DisplayObject> #end {
```
to
```haxe
extern class DisplayObject extends EventDispatcher implements IBitmapDrawable implements Dynamic<DisplayObject> {
```

(needed some fix in flash/Boot.hx)

but that can still make some runtime crashes if you do
```haxe
package;

import flash.display.Sprite;

class Main extends Sprite  {
    public function new() {
        super();
        trace(new Sprite().foo.alpha);
    }
}
```
and not just on flash, but also the other targets.

Well less likely to pass compilation, but still.

So I'll remove those, if things breaks well my bad can always revert,
but considering the amount of error this bring implementing Dynamic isn't worth it.

@jgranick please specify the exact need this was added for and we'll look into a solution for it.

**Comment by kasparsj** [comment]
@ibilon getting now runtime errors with flash and https://github.com/openfl/swf:
`ReferenceError: Error #1056: Cannot create property instance9 on format.swf.lite.MovieClip.`

**Comment by ibilon** [comment]
Maybe it'd make sense to have the `implements Dynamic` in the swf class, since it expects it and you're not supposed to use it directly.

@kasparsj could you send a swf where that happens?

**Comment by kasparsj** [comment]
Here is a test file.
However adding 
`implements Dynamic` to `format.swf.lite.MovieClip` fixes it.
[test.swf.zip](https://github.com/openfl/openfl/files/244847/test.swf.zip)

**Comment by kasparsj** [comment]
@jgranick I'll create a pull request

**Comment by jgranick** [comment]
This still breaks recursion:

```haxe
var clip = Assets.getMovieClip ("library.myclip");
clip.child1.child2.x = 100;
```

**Comment by jcward** [comment]
@Gama11 - I get a compile-time error when I try your testcase:
```
src/Main.hx:24: characters 4-20 : openfl.display.DisplayObject cannot be called
```

The above attempted fix -- implementing Dynamic on MovieClip isn't recursive because after the first call, the type has been resolved to DisplayObject -- and rightfully so.

Did you guys see my posts on slack? I believe the way to properly handle this is with an abstract, because it's purely a compile-time issue, a typing issue. We have:
- a DisplayList with containers (DisplayOBjectContainer) and non-containers (DisplayObject)
- the container obviously extends the non-container
- we don't want the basic non-container (DisplayOBject) to be Dynamic
- but we do want one certain container (MovieClip) to be dynamic
- but how can we ensure this dynamic-ness is maintained if the type returned by the dynamic resolve is the basic DisplayObject?

This is exactly what my sample here solves: http://try.haxe.org/#20d5f

It's a tree with a basic Node type and a NodeContainer, but also a DynamicNodeContainer (aka DisplayObject, DisplayObjectContainer, and MovieClip.)

Here's a gist of how the concept might be applied to MovieClip: https://gist.github.com/jcward/8cc4ef697cdd8d11b760b72e0bed0fa6

However, there are a few practical problems with this:

- It relies on abstract @:resolve, which only exists in haxe 3.3
- It relies on a bugfix for @:resolve, which isn't fixed yet. (https://github.com/HaxeFoundation/haxe/issues/5097) -- simn marked it as milestone Haxe 3.4

In the short term, perhaps we should just stick with the dynamic on DisplayObject. (And figure out why @Gama11's testcase is a runtime error -- when I run that same code, I get a compiletime error.)

**Comment by ibilon** [comment]
@jcward did you test on flash? it was `implements Dynamic` not `Dynamic<DisplayObject>` on it

**Comment by jcward** [comment]
@ibilon - ah, indeed, when targeting flash the error is not caught at compile-time. Why is that?

Also, I don't understand your second sentence. What was `implements Dynamic`, and what is the significance of it? My version of openfl DisplayObject.hx has `implements Dynamic<DisplayObject>` and I still get the runtime error in flash...

**Comment by ibilon** [comment]
Flash uses the extern/flash/display/DisplayObject.hx file,

the difference is that `implements Dynamic<DisplayObject>` assume a missing identifier is a DisplayObject and `implements Dynamic` a Dynamic.

You can do `trace(new Sprite().foo.alpha);` and it'll crash at runtime,
foo is unknown? so it's a DisplayObject, which has an alpha property.
The only thing is foo doesn't really exist.

**Comment by jgranick** [comment]
I had used `implements Dynamic` in the Flash, since in Flash, you can `myMovieClip.myNewProperty = "lakjsdf";` if you want

This does not work on static Haxe targets, this will cause errors when you have getter/setter properties. It needed to be `Dynamic<DisplayObject>` in order for `clip.x` to resolve to `clip.get_x`, etc.

This is a tough issue, but for porting ActionScript projects, and for FLA content, I think the recursion is really important. Compare:

```haxe
myClip.child1.child2.child3.child4.visible = false;

...

cast (cast (cast (myClip.getChildByName ("child1"), DisplayObjectContainer).getChildByName ("child2"), DisplayObjectContainer).getChildByName ("child3"), DisplayObjectContainer).getChildByName ("child4").visible = false;
```

I understand the frustration of not catching a spelling error until runtime, though I feel that the non-descript "DisplayObject cannot be called" error is an issue we should report to Haxe, it should return a better error when a resolve fails.

I'd like to keep dynamic access (as it has no performance cost to projects that don't rely on the dynamic access) but if we could improve the ergonomics in the future (like with the abstract resolve idea), I'm for it. We could do #if conditionals around the Haxe version used

**Comment by jcward** [comment]
> We could do #if conditionals around the Haxe version used

I had forgotten about that. So the abstract might possibly be useful.

In the short term (or for haxe <3.4) -- I think two things are interesting:
- The flash externs having `Dynamic<DisplayObject>` is better than just `Dynamic` -- it will turn @Gama11's case (the common function/property misspelling) into a compile-time error (right?). While there are still possible crash cases (as @ibilon pointed out `new Sprite().foo.alpha`) that's a much smaller surface for error - you have to have dot access multiple sub-objects.
- As mentioned, it sounds like this behavior could be optional, and many prefer opt-in. Perhaps it'd even be possible to do:
  - Default off, but
  - Default on in the `format.swf` library is loaded -- would this make everyone happy and make @kasparsj test swf work out of the box?

**Comment by jcward** [comment]
> I had used implements Dynamic in the Flash, since in Flash, you can myMovieClip.myNewProperty = "lakjsdf"; if you want

Oh, I had missed that part. So implements Dynamic<DisplayObject> is not compatible with this?

**Comment by jcward** [comment]
Ok, I'm trying to model how this works today in OpenFL with the simple node test, and I can't make it work:

http://try.haxe.org/#52935

Like OpenFL, the base type has the `implements Dynamic`, the container has the `function resolve`, but none of it's working. Any ideas?

**Comment by jgranick** [comment]
I put the 'resolve' under 'DisplayObject', not the container. The resolve returns only a standard DisplayObject, so that is where the resolve must be to continue chaining

**Comment by jcward** [comment]
This guy just had the same typo I did, leading to the same strange error message. This is sadly un-Haxe-like. :(

http://stackoverflow.com/questions/38833158/why-does-lib-current-stage-give-me-an-error

![image](https://cloud.githubusercontent.com/assets/2192439/17494590/9a404690-5d72-11e6-9e30-da396cfd8fde.png)

**Comment by jgranick** [comment]
Is there an issue open on haxefoundation/haxe in order to correct this error message?
