### ISSUE TITLE
gl issue GL Error: 1282 13x15

### ISSUE THREAD

**Issue by lovedna** [openfl/openfl#1099]
i get an error on neko target 

GL Error: 1282 13x15

where can i get error code list and  details

**Comment by IBwWG** [comment]
I also see this on the command line with windows/debug, very randomly, it seems.  @player-03 had posted something [here](https://gist.github.com/player-03/01cd027edc49c31521f6) that I meant to look into for this issue.

**Comment by ibilon** [comment]
Is that everything the app is printing? If not in debug mode does `openfl test neko -debug` print more?
Does it crash or keep going, if it does how do things look, ok or all black?

What version of lime and openfl are you using?
What operating system are you on, and do you know what graphic card do you have?

Can you try with a native build: `openfl test linux -debug` (or windows or mac instead of linux, as appropriate)

**Comment by IBwWG** [comment]
For me, everything looks absolutely normal, and nothing crashes.  It just randomly spits out this message once in a while.  Sometimes more often, sometimes less.  Seems to happen less since 3.6.0->3.6.1 and lime 2.9.0->2.9.1.  This is a native build, windows/debug.  I don't have my project running on neko currently, unfortunately.  Win7x64, integrated Intel HD graphics (on a laptop) with 2 GB shared video ram.

**Comment by ibilon** [comment]
Maybe it's trying to use an unavailable opengl command.

@lovedna @IBwWG what are your OpenGL version?

**Comment by IBwWG** [comment]
3.6.1 as I said, but this seems to happen more frequently on 3.6.0.

**Comment by ibilon** [comment]
No the open**GL** version.

**Comment by IBwWG** [comment]
LOL, my bad!  I'm not sure, actually.  Is there an easy way to output that using openfl?
