### ISSUE TITLE
EventDispatcher ignores nested events of same type

### ISSUE THREAD

**Issue by TomByrne** [openfl/openfl#1100]
There is a problem with how EventDispatcher dispatches events of the same type.

If an event is fired with the same type as an event that is currently being dispatched, it gets ignored.
Unfortunately this breaks Event.ADDED in many circumstances, and as a result breaks several MVC libraries which are watching for views being added to the stage.

This is the problematic process flow:
- DisplayObject gets added to stage
- Event.ADDED is dispatched and gets caught by some system
- Somewhere within the handler, a child DisplayObject is created and added to the first view
- An ADDED event gets dispatched on this child, which then bubbles to the parent DisplayObject
- The parent DisplayObject goes to dispatch the event, but as it is already dispatching a Event.ADDED the new event it is ignored.

The line which does the ignoring is 199 (in EventDispatcher.hx @ commit f68e4da).

Fixing this is not so trivial, as the __newEventMap/__dispatching collections are only designed to track a single dispatching event.

**Comment by ibilon** [comment]
I intend to test these pull requests this week,
could you post a code sample showing this issue?

**Comment by Leander1P** [comment]
I probably cannot until Tuesday, apologies, but will try to then.  Would very much like to back it up with asserts (any suggestions about how to do asserts?) and tests.  Note #1105 is a different approach than #1101, I saw some other possible bugs and went with a deeper refactor. If you'd like I can base 1105 on 1101.

We had at least one instance where an addEventListener in a callback was enough to get a different unrelated type listener to fire when it wouldn't with the old code.  Will try to reduce that to a testcase.

**Comment by ibilon** [comment]
No worries, there's a lot of bugs for me to see until then ;)

**Comment by Leander1P** [comment]
Okay, I'm having a bit of a time coming up with reliable testcases here -- hopefully @TomByrne may be able to help with a formal version of what he mentioned in the original post?

In the interim, I'm going to comment below with the points that I think might cause problems and attempt to derive some testcases from those, and revisit our most recent game codebase to see if I can extract a reliable exact pattern for a testcase from the issue we saw.

Roughly, in the original code, things that should be able to convert to tests:

1. **Dispatching goes false too soon**: The reset of dispatching at the tail of `__dispatchEvent`, namely the `__dispatching.set (event.type, false);` line, is unconditional.  Clearly we want to keep dispatching true if we're nested, so we should only unset that if we're the "outermost" dispatcher.
2. Possible **early __newEventMap discard**: In `removeEventListener` and the tail of `__dispatchEvent`, the original code can `null` out both `__eventMap` and `__newEventMap` at the same time based on only `__eventMap` being empty (`!__eventMap.iterator ().hasNext ()`).  It's reasonable to imagine cases where we have pending changes to `__newEventMap` for an unrelated type that are not committed back to a now-empty `__eventMap`.  I'm not sure this is actually possible in the original code, it takes some care to avoid cases where there is an empty `__eventMap`, but it might be given the first bullet (incorrectly dropping "are we dispatching" back to false once we exit the innermost nest).
3. Possible **stomp over all of __dispatching**: Similarly, where we `null` those two, we don't `null` out `__dispatching` at the same time.  The next `addEventListener` call will replace the current `__dispatching` with a new one, blasting over any dispatch-in-progress bools.
4. **Use of not-yet-populated entry in __newEventMap**: The first `if (list == null) return false;` return in `__dispatchEvent`, as pointed out by OP, is problematic: if you dispatch FooEvent, don't add or remove listeners, and dispatch it again within a listener (taking care not to infinitely recurse using a bool or somesuch), you'll get a null `__newEventMap`.  This is the only one I've really successfully gotten a NOT OK / ok test result from:

```
class Main extends Sprite 
{
	var o:DisplayObject;
	var test01aCallCount = 0;
	private function test01a (e:Event):Void {
		++test01aCallCount;
		if ( test01aCallCount == 1 ) { // avoid infinite recursion, but we still should get a second call
			o.dispatchEvent( new Event("Test01Event") );
		}
	}
	public function new() 
	{
		super();

		o = new DisplayObject();
		o.addEventListener( "Test01Event", test01a );
		o.dispatchEvent( new Event( "Test01Event" ) );
		trace ( (test01aCallCount == 2 ? "ok" : "NOT OK") + ": Expected call count of 2 for test01a, got " + test01aCallCount );
	}
}

```

It also strikes me that we shouldn't need this block at all:

```
			if (listener == list[index]) {
				
				index++;
				
			}
```

...and can just unconditionally bump index (e.g. in a for loop) if we're not accidentally mutating lists somewhere.  Full discards or replacements of lists don't trigger the behavior because the loop retains a reference to the original list, so the 1->0 and 0->1 size cases don't tend to exhibit drastically bad behavior here -- but I have a feeling there'd be a way to make that [index] out of bounds with a little trying.

Hopefully that helps to start.  I'll dive into testcases for the other issues above and the problem we saw in our codebase (up at http://fiscalship.org/ now btw, as a "yay team") tomorrow.

**Comment by Leander1P** [comment]
I'm having trouble exploiting the others, partly (fortuitously) due to the effects of "Use of not-yet-populated entry in __newEventMap".

Here's a test:

```
	var o:DisplayObject;
	var test02aCallCount = 0;
	var test02Sequence:String = "";
	private function test02a (e:Event):Void {
		test02Sequence += "a";
		++test02aCallCount;
		if ( test02aCallCount == 1 ) {
			test02Sequence += "(";
			o.dispatchEvent( new Event( "Test02Event" ) );
			test02Sequence += ")";
			
			// dispatching should still be true here, so this shouldn't modify the list we're traversing over
			// ...but it does...
			o.removeEventListener( "Test02Event", test02a );
			o.removeEventListener( "Test02Event", test02b );
			o.addEventListener( "Test02Event", test02a, false, 4 );
			o.addEventListener( "Test02Event", test02b, false, 5 );
		}
	}
	private function test02b (e:Event):Void {
		test02Sequence += "b";
	}
	private function test02c (e:Event):Void {
		test02Sequence += "c";
	}
	public function new() 
	{
		super();
		o = new DisplayObject();
		// Test 02: Dispatching goes false too soon.
		// The reset of dispatching at the tail of __dispatchEvent,
		// namely the __dispatching.set (event.type, false); line, 
		// is unconditional. Clearly we want to keep dispatching true 
		// if we're nested, so we should only unset that if we're the
		// "outermost" dispatcher.
		o.addEventListener( "Test02Event", test02a, false, 3 );
		o.addEventListener( "Test02Event", test02b, false, 2 );
		o.addEventListener( "Test02Event", test02c, false, 1 );
		o.dispatchEvent( new Event( "Test02Event" ) );
		trace ( (test02Sequence == "a(abc)bc" ? "ok" : "NOT OK") + ": adds or removes should not mutate a list we're currently traversing; wanted a(abc)bc and got: " + test02Sequence );
	}
```

Note that it's tricky to get this to fail for "Dispatching goes false too soon" reasons, because that doesn't happen in this test due to the "Use of not-yet-populated entry in __newEventMap" (it'll return `a()bc` in that case, still not what is wanted, but for a different reason).  If you fix that naively, by just looking for an entry in `__eventMap` if there's none in `__newEventMap`, you might get something like `a(abc)bac`.  What we want is `a(abc)bc` -- the two dispatches should happen in `abc` order, with the inner dispatch between.

Should I be aiming for another commit that puts these tests in https://github.com/openfl/openfl/blob/develop/tests/test/openfl/events/EventTest.hx ?

Likely to get pulled off onto other projects imminently here.  =( May not be able to return to this for a bit.  Trying to get a bit more time in on it today before stopping, though.

**Comment by Leander1P** [comment]
Updated #1105 with some commented out asserts (ran our game and the above tests with these) and some more cleanups and dedupes.

Holler if you want EventTest.hx updates.

**Comment by nikolay-mamaev** [comment]
Is the following fix OK (see `__newEventMap.set (type, list.copy());`)?

    private function __dispatchEvent (event:Event):Bool {

        // ...

        if (__dispatching.get (type) == true) {
            list = __newEventMap.get (type);
            if (list == null) return false;
            list = list.copy ();
        } else {
            list = __eventMap.get (type);
            if (list == null) return false;
            // The line below is the fix:
            __newEventMap.set (type, list.copy());
            __dispatching.set (type, true);
        }

        // ...

**Comment by Leander1P** [comment]
@nikolay-mamaev I believe it will fix (4) above in https://github.com/openfl/openfl/issues/1100#issuecomment-214902204 as it is listed there, but I worry that it hasn't gotten the other edgecases, and it's provably more work (it pessimistically assumes you need to make that list copy before anything has tried to modify the list of listeners).  JGranick mentioned that he wanted to avoid this kind of pessimistic overhead in https://github.com/openfl/openfl/pull/1105#issuecomment-221372862 .

I'm going to try to break up #1105 into a patch sequence, starting with the "don't set dispatching false until we leave the outermost dispatch" and working through the other fixes, then the refactors, but it's probably going to take a while before I get to this (I'm not even working with Haxe/OpenFL/Lime in any projects at the moment, although I am peripherally supporting a few).  =(  I've found it difficult to prove the behavior of small fixes the way it's written, hence the overhaul, deduplication, and such in #1105.

**Comment by jgranick** [comment]
Hey guys

I fixed this use case, of two event dispatches in a row, nested. @Leander1P you raise some important points. I know that a list.copy at the beginning of a dispatch would solve all these problems, but I wanted to avoid doing so because of the burden it would put on garbage collection. That's where the "newEventMap" came from, but I know this is an imperfect system.

Do you think that using an `Int` for `__dispatching` (instead of `Bool`) would help solve problems of embedded dispatches inside of embedded dispatches, or we going to inevitably run into a problem of this eventually breaking if you use the right combination of add/remove event listener, plus dispatches?

**Comment by Leander1P** [comment]
@jgranick No real need to switch to `Int`; the nesting depth should be inherently kept in the arrangement of the stack frames.  All you need to know is when the outermost dispatch returns.  See https://github.com/openfl/openfl/pull/1105/commits/93b3e4a489d4e45b76426cf96189089a98f6cdd3#diff-093bdd3a872540af6c72eafb5386f796R261 -- one local `Bool` in the `__dispatchEvent` method, plus the `Bool` map (type key -> `Bool` value).  The introduction of this `outermostDispatch` bool would be the first small patch in the patch chain that leads up to #1105, if I get a chance to pull it apart, since I think it's the single most important piece.  I don't think it's the only piece, but it solves most of the actually observed problems after the cd17847 null-list thing.

**Comment by Leander1P** [comment]
Just as a for-what-it's-worth, your change at https://github.com/openfl/openfl/commit/cd17847fbaf4091374ae7da8446a98c3bffe42ee#diff-093bdd3a872540af6c72eafb5386f796R199 corresponds to this bit here in #1105: https://github.com/openfl/openfl/pull/1105/commits/93b3e4a489d4e45b76426cf96189089a98f6cdd3#diff-093bdd3a872540af6c72eafb5386f796R97
