### ISSUE TITLE
graphics.lineTo CPP memory leak 

### ISSUE THREAD

**Issue by MiltonW** [openfl/openfl#1117]
Seems to be ok in Neko, HTML5, but CPP (linux):
```
this.graphics.clear();                                                  
this.graphics.lineStyle(0, 0xFFFFFF);                                   
this.graphics.moveTo(0, 0);                                             
this.graphics.lineTo(Math.random()*100, Math.random()*100);      
```

see http://community.openfl.org/t/memory-leak-removechild/7636

**Comment by jeichelbaum** [comment]
ah thanks a bunch was just about to submit this!

**Comment by MSGhero** [comment]
Does it also happen when you call other draw commands, like `curveTo` or `drawRect`? Does it happen if you remove the `lineTo` but leave the rest of the code? And does it still happen if you change the `lineStyle` parameters up?

**Comment by MiltonW** [comment]
without lineTo: no leak
with different lineStyle: leak
curveTo: leak! (maybe add to issue title?)
drawRect: no leak
drawCircle: no leak
drawEllipse: no leak

lime 2.9.0 / openfl 3.6.1

**Comment by jgranick** [comment]
Is this using legacy?

**Comment by MiltonW** [comment]
No. 3.0.x/4.0.x still leaks.

**Comment by jgranick** [comment]
I am not seeing a leak.

Testing with the following code:

```haxe
package;


import openfl.display.Sprite;
import openfl.events.Event;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var sprites = [];
		
		for (i in 0...100) {
			
			var sprite = new Sprite ();
			addChild (sprite);
			sprites.push (sprite);
			
		}
		
		addEventListener (Event.ENTER_FRAME, function (_) {
			
			for (sprite in sprites) {
				
				sprite.graphics.clear ();
				sprite.graphics.lineStyle (0, 0);
				sprite.graphics.moveTo (0, 0);
				sprite.graphics.lineTo (Math.random () * 100, Math.random () * 100);
				
			}
			
		});
		
	}
	
	
}
```

Memory use climbs, until a point where the garbage collector triggers and cleans up old memory. This behavior is defined in HXCPP. I believe that in more recent versions, there was a change that caused the collector to run less frequently if memory was "not too high." On my system, it appears to run around 110 MB.

The test creates a lot of GC activity, because `Graphics` is designed to allocate a surface that is exactly the size needed for its contents. If you had a solid fill that was larger than the random line drawings, the size would remain consistent, it would not create new surfaces.

You can change the number of sprites from `100` to a lower number in the above test. Changing it to `1` takes the longest to trigger garbage collection, but I have left this test running and it never crashes or spikes to extraordinary levels.

If the trigger point for GC is not triggering well on your system, we should report that to HXCPP. Thanks :smile:

**Comment by MiltonW** [comment]
I don't quite agree.

`sprite.graphics.drawCircle(Math.random () * 100, Math.random () * 100, 50);`
![circle](https://cloud.githubusercontent.com/assets/6236680/17534231/7c608f24-5e88-11e6-99af-cdf485df455e.png)

`//sprite.graphics.drawEllipse(Math.random()*100, Math.random()*100, 50, 20);`
![ellipse](https://cloud.githubusercontent.com/assets/6236680/17534239/814f4516-5e88-11e6-8785-68d06caeea0b.png)

These work fine. Memory doesn't get any bigger than that. **lineTo**, **curveTo**, and **drawRect** just keep going. Sometimes the memory gets cleaned, but eventually it grows again. But only CPP, neko works fine.

**Comment by SeanHogan** [comment]
I'm getting this same issue. Running next, openfl 3.6.1. Calling lineTo over 10 seconds will have windows showing my modified memory increasing at 300 MB per second or so, even if I'm only drawing one line at a consistent position.
