### ISSUE TITLE
Instantiation of a child class of DisplayObject will show up a white screen

### ISSUE THREAD

**Issue by buckle2000** [openfl/openfl#1125]
This project works fine on windows, html5, but **not on flash.**
_This Project:_ https://gist.github.com/buckle2000/fd74fd6a164ca2c895f87151c1d07568

**Comment by jgranick** [comment]
This is the real issue:

https://github.com/HaxeFoundation/haxe/issues/4550

This should be a compile error

From the AS3 library documentation:

> DisplayObject is an abstract base class; therefore, you cannot call DisplayObject directly. Invoking new DisplayObject() throws an ArgumentError exception.
> 
> The DisplayObjectContainer class is an abstract base class for all objects that can contain child objects. It cannot be instantiated directly; calling the new DisplayObjectContainer() constructor throws an ArgumentError exception.

**Comment by tienery** [comment]
Not really, because Haxe doesn't assume anything about `extern` classes. The reason for this logic, I presume, is because the generated code is going to be locating to something inside of another API, which Haxe itself has no control over. There's no point in the Haxe compiler in throwing an error at you for a language it cannot parse/interpret.

I don't think that's the "problem", the nature of Haxe when it comes to extern classes is that it doesn't assume anything. It will generate a compiler error on the target side, like when you create a C++ extern for a class and mix up one type in Haxe with another type in C++, it's not Haxe that throws the compiler error, the C++ compiler does.

It makes the most sense just to pass what Haxe interprets in its own language to the target language, and let the target language's compiler determine what's wrong. In this case, the Flash Compiler probably won't complain because Haxe is generating code at the Haxe level, not the Flash level, so by the time it reaches the Flash level to be compiled to SWF, the Flash Compiler is reading the accessors and then thinks... "You've given me code that I can't compile."

It will work on other targets because those targets don't have the same limitations or interpretations as Flash, they all work differently, so Haxe finds a middle ground, and that middle ground is: "If externing to a type in Flash, let's not assume any of the accessors will work. Just pass it anyway, and see what happens, let the target language compiler decide what's wrong."

As far as I am concerned, that's the best policy.

**Comment by jgranick** [comment]
The problem is that our `private new` constructor for `DisplayObject` and `DisplayObjectContainer` is ignored, but for some reason, if we rename `openfl.events.EventDispatcher` to `openfl.events.EventDispatcher2` and change the inheritance accordingly, it works. I'm not sure why in the current case, the compiler doesn't throw an error if you try to `new DisplayObject ();`

**Comment by tienery** [comment]
I'm currently experimenting, I thought I'd change the `EventDispatcher` constructor to `private` but that made no difference whatsoever, it seems, in the lack of compiler error, which is a bit odd since `EventDispatcher` fall back on anything else.

**Comment by buckle2000** [comment]
@jgranick what's more, there is an error if you do **not** call `new DisplayObject ();`
