### ISSUE TITLE
iOS project.xml -> XCode project issues/questions/suggestions

### ISSUE THREAD

**Issue by revanaii** [openfl/openfl#1154]
Some problems/questions were encountered with the generated XCode(7.3.1) project.

1) 
`<window fullscreen="true" borderless="true"/> `
and still "Requires full screen" has to be manually enabled in the XCode project each time.

2) Is there any way to link an objective-c library(.a) in project.xml ?

3) Is there any way to enable the provisioning profile and certificate in project.xml ?

4) Is there any way to enable capabilities(like iCloud/IAP/GameCenter) in project.xml ?

The problem is that each time the XCode project gets re-built I have to do all those things manually over and over again.
Maybe some of those features are already available and I just don't know how to use them.
In this case could you please point at the corresponding documentation?
Thanks.

**Comment by Yanrishatum** [comment]
3) Yes! `<certificate identity="iPhone developer/distribution <name> (<ID>)"` E.g. your certificate identity from keychain. And you need to drop mobileprovision file into XCode that related to that identity. Only once. And you need to disable it for simulator.

**Comment by jgranick** [comment]
1.) This should be added in current versions
2.) Yes, using the `<dependency path="" />` tag (or use `name` instead of `path` if it is a global library)
4.) There are native extensions to allow IAP, GameCenter, etc :smile:

Please feel free to join http://community.openfl.org, it's the best place to discuss things like this :smile:
