### ISSUE TITLE
[OSX 10.11.2] Uncaught exception - std@module_read

### ISSUE THREAD

**Issue by man2** [openfl/openfl#1160]
I got this:
Uncaught exception - std@module_read

when trying to run my neko program using openfl / lime test neko on my mac osx 10.11.2
Haxe 3.2.1
NekoVM 2.1.0

**Comment by MiltonW** [comment]
This is a Neko size limit thing.

    <haxedef name="no-inline" if="neko"/>
    <haxedef name="dce=full" if="neko"/>

should fix it.

**Comment by man2** [comment]
got this when using dce=full

Called from ru.stablex.ui.widgets.Widget::set_top line 767
Called from openfl.display.DisplayObject::set_y line 1457
Uncaught exception - Invalid field access : ty

**Comment by MiltonW** [comment]
I can't really respond to this, unless you can share your code. Invalid field access usually means you haven't initialized the object.

**Comment by jgranick** [comment]
This error is being caused by dead-code elimination ("dce"), which is removing a field it thinks your project is not using. DCE reduces the size of your project, but may not be enough to make it small enough for Neko 2.0, Neko 2.1 has fixed this by increasing the maximum size of a Neko project, in Lime, we use an inbetween development build of Neko 2.0 that had this patched, but I think this might not have been patched for Mac

We need to integrate Neko 2.1 in our Lime tools binaries, and sort any differences on our end to support the newer version. This will fix the issue for Mac, in the meantime, I would recommend using `openfl test mac` instead of Neko for this project until we update

**Comment by man2** [comment]
thanks for the clarification. Hope this get sorted out soon, it's taking a long time to compile each time I want to test my game using "openfl test mac".

**Comment by jgranick** [comment]
A new version of Neko was released, which raises the maximum application size limit -- we don't have this included in Lime yet, but this would be the best way to fix this
