### ISSUE TITLE
ByteArray issues

### ISSUE THREAD

**Issue by chpla** [openfl/openfl#1193]
Since updating to openfl 4.0.0 I observe several issues with ByteArray (html5 target).

First, it seems that when I set the .length property to a value greater than the current length of the array, the added fields are not always initialized with zeroes (as they are in as3) but sometimes (unpredictable) with (seemingly) random values.

Also, the .writeBytes method throws an OutsideBounds error when I submit a length parameter greater than the length of the source array (after the given offset). This behavior is unlike as3, where the length parameter gets capped to the maximal possible value according to the source array.

There seem to be more bugs, which I haven't found yet. This has caused some encryption functions to fail in my case and it's giving me headaches trying to figure this out and work around it... so if anybody else is having similar issues, please share your information! Thanks

**Comment by jgranick** [comment]
I am giving the following a try:

```haxe
var byteArray = new ByteArray (10);
byteArray.writeByte (1);
byteArray.length = 101;

for (i in 0...byteArray.length) {
	
	trace (byteArray[i]);
	
}

var byteArray2 = new ByteArray (99);
for (i in 0...byteArray2.length) byteArray2[i] = 3;

byteArray.writeBytes (byteArray2, 0, 200);
```

On both Flash and HTML5, I get 0 values when I trace the resized `byteArray`, but this might be unspecified behavior in HTML5. What browser, version and OS are you testing with?

As for the `writeBytes` call, I get a `RangeError` in Flash Player when I use a value greater than the target  ByteArray, or the source. `99` or less is the only value that worked for me here

**Comment by chpla** [comment]
I could not replicate this in simple cases, unfortunately. Something bad happens to the BitmapData in our AES encryption routine and I can't quite figure out where it goes wrong. I just know it has to be due to some different behavior between 3.*.* and 4.*.*. When the backend tries to decode the encrypted message, it's an incomprehensible mess.

**Comment by chpla** [comment]
I'll have to do a side-by-side comparison between the as3 and the haxe version, then I can hopefully figure out where exactly things are going wrong. Going to do this by monday I hope!

**Comment by jgranick** [comment]
Thank you for your help!

**Comment by jgranick** [comment]
We have made fixes to `ByteArray` since summer, included fixes to endianness support on a couple key functions. I have just now added changes to make sure that native fills allocated memory with zeros.

As far as I know, things are working properly. Even though the documentation for `writeBytes` says that the offset and length will be trimmed if they are too large, the implementation in current versions of Flash Player through a `RangeError`, so I'm leaving our implementation on that alone for now.

Please let me know if you have more trouble with recent versions, or the latest source. Thank you so much :smile:
