### ISSUE TITLE
Optimize Vector<Int> and Vector<Float> to use Haxe Bytes

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1235]

**Comment by vroad** [comment]
What are you trying to do with this? Does that really improve performance?
I'm not sure how this can be implemented without sacrificing performance in any situations. Bytes.setFloat is slow on js because DataView is not so optimized as typed arrays.

For me using Vector has been pain. It's slower than arrays, makes a deep copy when converting to arrays, because underlying storage is not compatible with Array. I want Vector to use Arrays because that will cause less amount of troubles.

**Comment by jgranick** [comment]
I think that if (at the very least) `Vector<Int>` or `Vector<Float>` can map to `Int16Array` and `Float32Array` respectively, it will speed up use with Stage3D, and can probably out-perform `haxe.ds.Vector`

`Vector` is an abstract, so it can be anything

**Comment by vroad** [comment]
Can that be done without using extensive use of if statements? Using if statements in a loop can make performance even worse than `Array`. And that will only work efficiently if fixed is true.

I think there are other things we can do about performance. First of all, do not use inline too much. I'm not sure about neko and flash, but modern JavaScript engines, C++ compilers, and .NET JIT are smart enough to inline function calls when it's appropriate. Inlining by Haxe does not have side effects if you use that for functions which have few statements, but if you use this for big functions, that will just make caller function bigger. And such big functions will not be inlined by compilers. So using inline does not necessary improve performance.

Using functions already exists in `Array` will also improve performance, because it only needs one statement, and I guess `Array` is already heavily optimized on all targets. Using `haxe.ds.Vector` or typed arrays will make this optimization impossible. What if you push (or make out-of-range access) elements to non-fixed `Vector`?

Original AS3 Vector implementation throws errors if you try to push something to fixed Vector, but current OpenFL implementation does not throw at all. It just ignores such calls. Since it's only useful when debugging, I'm thinking of omitting these checks unless some compiler flag is defined.

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/Vector.html#push()

**Comment by vroad** [comment]
So I have been thinking that backing `openfl.Vector` with Array instead of `haxe.ds.Vector` or typed arrays would be a reasonable compromise.

If uploading performance is concern, I would recommend using typed arrays directly. That way you could achieve good performance on most platforms. On Flash it could be uploaded to vertices/indices as ByteArray. Flash ByteArrays some overhead compared to `Vector`, but its performance is not so bad.

**Comment by vroad** [comment]
'haxe.ds.Vector' is slow for resizing, because it needs to blit existing content even if platform supports more efficient way of resizing. We could probably avoid this issue by using some platform-specific code (or by using `Array`?).

Also, `Vector<UInt>` is converted automatically to 16bit unsigned int when uploading to a Stage3D index buffer. So your solution does not work for indices at least.

**Comment by vroad** [comment]
`Float` is double precision on Haxe, so you cannot directly upload `Vector<Float>` to Stage3D vertex buffer (which is single precision) either.

**Comment by jgranick** [comment]
I have taken the first steps to make an `openfl.Vector` abstract that is multi-type -- this has had a big impact on C++ performance. For now, it's still an `Array` type, but with specialized abstracts, performance over the previous implementation has made the Starling benchmark run 6.5 times faster. I'm still interested in upload performance, but already this has had a big impact

**Comment by vroad** [comment]
Is it meaningful to have implementations that are backed by primitive type `Array`? Why is there `FunctionVector`, isn't that an object type as well? 

I believe `Vector<Int>` is automatically backed by `Array<Int>` if you use template type `Array<T>`. Isn't that true?

I don't think it's possible to use typed arrays as storage, because there are precision differences, so I thought that one implementation is enough.

**Comment by jgranick** [comment]
We could perform tests using `Array<T>`, but I believe C++ is a lot happier with the current implementation. For one, it does solve some problems, such as initialization with default values.

`FunctionVector` is there because function equality does not work on all platforms without using `Reflect`, so that solves some issues such as `indexOf`

**Comment by vroad** [comment]
Hhm, C++ target does not create separate class implementations per type params even if I use `@:generic`. Is this a known issue of Haxe?

https://haxe.org/manual/type-system-generic.html

But even if it works, I don't want Haxe to create implementations for all object types. Probably we could use `@:genericBuild` instead, but that would make Vector code more complex.

`FunctionVector` may fix equality check issues with `Vector`, but I'm not sure if that's correct way to fix that. I guess equality checks still fail with other containers.

**Comment by vroad** [comment]
Did you test with other targets? I tested new implementation on C# and didn't work.

https://github.com/openfl/openfl/blob/8e776de75415eb1033724e81d3ab65af7674882b/openfl/Vector.hx#L1661

On C# `Vector` fails to set length when fixed is enabled. And unlike Flash this does not throw exceptions at all.

Currently non-cpp targets are using `push` to initialize elements, but some targets may have more efficient way to resize. For example, on js you can directly set length field with `untyped`. C# has target-specific function (`Array.alloc`).

At least on C# and js it's not helpful to use multiple implementations, because C# supports instantiation of each template classes at runtime, and js is a dynamic target.

**Comment by jgranick** [comment]
How many changes do I need in order to test C#?

**Comment by vroad** [comment]
You need some changes to lime-tools to compile. Maybe there are other bugs/issues that prevents OpenFL from running. Well, but I've noticed that `cpp.NativeArray.setSize` will not be called either if fixed is true. But cpp doesn't have issues somehow.

I don't want to duplicate implementations across multiple classes because it makes changing code difficult...

**Comment by player-03** [comment]
> I don't want to duplicate implementations across multiple classes because it makes changing code difficult...

Very much agreed. If you want to create multiple very similar classes, I could write you a macro for that. Pretty sure I could set it up so that you can define a "`VectorTemplate`" class for the macro to copy.

If you explicitly defined a function (like `FunctionVector.indexOf()`) the macro would leave it alone. It would only fill in the functions you left blank.

---

Also, this breaks existing code because there's no `toArray()` function, and people are used to passing a `Vector` where an `Array` is needed. In fact, [some of the samples do it](http://community.openfl.org/t/why-does-openfl-samples-happen-failures-of-openfl-4-1-0/8130?u=player_03).

**Comment by sourceskyboxer** [comment]
Oh yes my consternation!

That is Openfl 4.1.0 Vector has bug!!!!
Openfl 4.0.3 is working fine 100 % I tested. Please re update openfl 4.1.0 with current version of Vector.hx from Openfl 4.0.3 Please replace old vector.hx from openfl 4.0.3 to Openfl.Vector.hx ( 4.1.0 )

Thanks for bonus fix!

**Comment by jgranick** [comment]
Against advice, I implemented to/from Array in the old vector type.

The new vector is much, much faster.

For good reason, we cannot use to/from Array, due to the following scenario:

```haxe
var vec = new Vector.ofArray ([ 1, 2, 3 ]);
var array:Array<Int> = vec;
array.push (4);
trace (vec); // [ 1, 2, 3 ]
```

If there is any conversion between underlying types (IE, if Vector is not an abstract over array) then it will make a copy, which creates some terrible errors. In the new (array-based) implementation, this would not occur on native platforms, but it will always occur on the Flash platform, and in the future, we may change Vector to being something other than Array under the hood.

I wish we could handle from array in the constructor only, but this is not possible with Haxe abstracts currently (like `var vec:Vector<Int> = [ 1, 2, 3 ];`)

**Comment by player-03** [comment]
> ```haxe
var vec = new Vector.ofArray ([ 1, 2, 3 ]);
var array:Array<Int> = vec;
array.push (4);
trace (vec); // [ 1, 2, 3 ]
```

I tested a couple different variants of this, and I always got `[1, 2, 3, 4]`. However, I wasn't able to test the version using `@:to`, because that wouldn't compile. As you said, it seems that making `Vector` a multi-type array completely changes the meaning of "`@:to`" and "`@:from`." (Why couldn't they leave those alone and pick different keywords for this?)

That said, this function seems to work fine (tested in Neko and C++ on Windows), and it would make a nice counterpart to `ofArray()`:

```haxe
public inline function toArray<T> ():Array<T> {
	
	return untyped this.__array;
	
}
```

The downside is that this will no longer work if you end up switching away from `Array`. If you're worried about that, have it return `Lambda.array (this)` instead. And maybe name it something like "`cloneAsArray ()`" so that people know what they're getting into.

---

On an unrelated note, `ofArray()` should take `Array<T>` rather than `Array<Dynamic>`, unless you have a really good reason for it. Sure, works at runtime, but `Array<T>` gives the compiler more information, leading to better inferences. For example:

```haxe
var f = function (?bool:Bool = false, ?int:Int = 0):Void {
	trace (bool + " " + int);
};

var vec = Vector.ofArray([ 1, 2, 3 ]);
f (vec[2]);
```

With `Array<Dynamic>`, this prints either "`true 0`" (C++) or "`3 0`" (Neko).

With `Array<T>`, it correctly prints "`false 3`."

**Comment by jgranick** [comment]
> The downside is that this will no longer work if you end up switching away from Array.

Yep, this is the case on the Flash target (by Adobe's design) and may be the case in the future. I'd like to help create consistent code :wink:

I think the reason for `Dynamic` is something like this:

```haxe
var vec:Vector<Float> = Vector.ofArray ([ 1, 2, 3 ]);
```

**Comment by sourceskyboxer** [comment]
Hello guys,

You know Vector hasn't bug but I find Float32Array from openfl has an issue possible. You know I have tested with NME library and NME's Float32Array is working and has not an issue while nme build or test into own windows binary than it works fine without errors...

![nme_simpleopenglview_better_than_openfl_lime](https://cloud.githubusercontent.com/assets/3496136/18359358/e0fd93f4-75f9-11e6-8044-58a4cd7ffced.JPG)

And read whole post from community.openfl.org
http://community.openfl.org/t/why-does-openfl-samples-happen-failures-of-openfl-4-1-0/8130

Thanks!
