### ISSUE TITLE
Graphics.drawTriangles appears broken on HTML5 target (OpenFL 4.0.3, Lime 3.0.3)

### ISSUE THREAD

**Issue by michaelapfelbeck** [openfl/openfl#1253]
Graphics.drawTriangle doesn't work with the HTML5 target.

When I try to use drawTriangles with HTML I get nothing rendered on the canvas and later solid color fills are also broken. I've tried running the HTML5 target in Chrome, IE and Edge; the results are identical.

Here's an example test case:
```haxe
    private function drawSun(){        
        var data:BitmapData = Assets.getBitmapData("assets/sun.png");
        var vertices:Vector<Float> = new Vector<Float>(8);
        var indices:Vector<Int> = new Vector<Int>(6);
        var uvtData:Vector<Float> = new Vector<Float>(8);
        
        vertices[0] = 0;
        vertices[1] = 0;
        
        vertices[2] = 100;
        vertices[3] = 0;
        
        vertices[4] = 100;
        vertices[5] = 100;
        
        vertices[6] = 0;
        vertices[7] = 100;
        
        indices[0]=0;
        indices[1]=1;
        indices[2]=3;
        
        indices[3]=1;
        indices[4]=2;
        indices[5]=3;
        
        uvtData[0]=0;
        uvtData[1]=0;
        
        uvtData[2]=1;
        uvtData[3]=0;
        
        uvtData[4]=1;
        uvtData[5]=1;
        
        uvtData[6]=0;
        uvtData[7]=1;
        
        graphics.beginBitmapFill(data);
        graphics.drawTriangles(vertices, indices, uvtData);
        graphics.endFill();
    }
```

Flash target result:
![flash](https://cloud.githubusercontent.com/assets/9601298/18031914/0208b862-6ca9-11e6-8559-fabeba30e8b9.png)
HTML5 target result:
![html5](https://cloud.githubusercontent.com/assets/9601298/18031916/1f9ce2c2-6ca9-11e6-866d-5b19c7c4c58e.png)

Edit: Included correct version #'s.

**Comment by scanline** [comment]
Hi!

I was about to recommend using the -Dwebgl switch but just realized that this just
works using OpenFL 3.6.1.
If I test your code using OpenFL 4.0.3 I get the same nifty black screen and additionally the following
error in the console:
**Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.**

**Comment by jgranick** [comment]
The culprit is this code:

https://github.com/openfl/openfl/blob/develop/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L987-L1135

Canvas does not have a parallel to `drawTriangles`, so its less of a straightforward implementation. I would appreciate if anyone would not mind taking a pass and seeing if its clear why it does not appear to work?

**Comment by scanline** [comment]
Definitely jgranick! Sadly I'm not the chosen one. ;)
By the way, forget about the WebGL error message - it's because FireFox executed within a virtual machine.

Anyway, as you said that part of the code is causing the issue with the canvas renderer - but why ain't WebGL working anymore since OpenFL 4.0.3? I coded another little test project which distorts a square constructed out of 2 triangles based on the position of the mousepointer. If I trace the dimesions of this shape, I can see it's changing with each mouse move - there's just nothing to be seen on screen unless I switch to OpenFl 3.6.1!

**Comment by mayakwd** [comment]
@jgranick, I guess the solution is to add line: `bitmapFill = c.bitmap;` between this two lines: https://github.com/openfl/openfl/blob/develop/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L662-L663

**Comment by mayakwd** [comment]
I mean - i checked this and drawTriangles works as expected after changing code in that way.
