### ISSUE TITLE
OpenFL 4.x rendering problem on iPhone 6s plus when allow-high-dpi is true

### ISSUE THREAD

**Issue by zengjie** [openfl/openfl#1309]
Recently, I am updating my openfl project to 4.x. But rendered graphic is smaller than before on iPhone 6 Plus and stays in the lower-left corner of the screen. I tried the PiratePig from the openfl-samples and got the same result.

But there is no problem when the games were running on iOS simulators.

![image](https://cloud.githubusercontent.com/assets/3864/19335581/fe75009a-9136-11e6-8363-f0dda88aa637.png)

Update: When `<window allow-high-dpi="false"/>` is set, there is no problem except for poor graphics quality.

**Comment by zengjie** [comment]
Update: This issue is still unresolved in OpenFL 4.4.1 / Lime 3.4.1.

This issue make the iOS target almost useless. :sad:

**Comment by jgranick** [comment]
I have not been able to reproduce this. Could you remove the app from your device, then try and install again? What version of Xcode are you using?

**Comment by zengjie** [comment]
I have tried to completely remove and reinstall the app and also tried different iOS devices.
The testing results are listed below.

**Building Environment:**

- Xcode: 8.1
- IPHONE_VER in .hxcpp_config.xml: 10.1
- OpenFL: 4.4.1
- Lime: 3.4.1
- Command Line: openfl update -clean ios

**Results:**
- iPhone 6s Plus: **not** ok
- iPhone 5s: ok
- iPad Pro: ok
- iPhone 6s Plus simulator: ok
- iPhone 6s simulator: ok
- iPad Air simulator: ok

Maybe it is related to screen rendering scale factors. The scale factor for iPhone 6s Plus is 3 (https://www.paintcodeapp.com/news/iphone-6-screens-demystified).

What iOS device are you using? @jgranick

**Comment by zengjie** [comment]
@jgranick I'm happy to dig the problem deeper. Would you like to give me some suggestions on where to start with? I have developed in C++ for over 10 years and made a mobile game (iOS/Android) with OpenFL 3.x legacy.

**Comment by jgranick** [comment]
The first question (I think) is if we are getting the correct events from SDL.

You could listen to `stage.addEventListener (Event.RESIZE, function (event) { trace (stage.stageWidth, stage.stageHeight));` from OpenFL, or `stage.window.onResize.add (function (width, height) trace (width, height));` for the Lime event.

I think that maybe this is not coming through, since we handle resize events in the "PiratePig" sample.

This is where SDL events come in:

https://github.com/openfl/lime/blob/develop/project/src/backend/sdl/SDLApplication.cpp#L109

I wonder if the issue is that the GL context is resized, but that we are not receiving the event, or if the size is reported incorrectly, or perhaps there is a chance that SDL is doing the right thing, but we handling it wrong somehow.

A little more investigation should help. My wife's iPhone 6 just stopped working, so I don't have anything to test with here (currently)

**Comment by zengjie** [comment]
Thanks for your suggestions. I'll investigate the problem this weekend.

**Comment by zengjie** [comment]
I have found the problem in Lime. 

https://github.com/openfl/lime/blob/develop/project/src/backend/sdl/SDLRenderer.cpp#L142

`double scale = outputWidth / width;`

should be

`double scale = double(outputWidth) / width;`

The correct scale for iPhone 6(s) Plus is 2.608696. Without type casting, the division operation was be an integer division, the result was 2.

**Comment by zengjie** [comment]
I have created a pull request in openfl/lime. @jgranick

**Comment by jgranick** [comment]
Awesome, thank you 😁
