### ISSUE TITLE
[HTML5] bitmapFill-ed sprites ignore mouse events.

### ISSUE THREAD

**Issue by RealyUniqueName** [openfl/openfl#1335]
```haxe
var s = new Sprite();
var bmp = Assets.getBitmapData('assets/pic.png');
s.graphics.beginBitmapFill(bmp);
s.graphics.drawRect(0, 0, 100, 100);
s.graphics.endFill();
addChild(s);
s.addEventListener(MouseEvent.CLICK, function(_) trace('clicked'));
```
This example compiled to html5 never traces "clicked". But if i change `beginBitmapFill` to `beginFill`, then everything works as expected

**Comment by mayakwd** [comment]
@RealyUniqueName Hi, the problem is behind this part of code: https://github.com/openfl/openfl/blob/b69abae749e09b4617c7bc73126cca1ac10e98bc/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L731-L784

Usually bitmap is rendering through method with optimisation, and context.drawImage is not using while hit-testing. Furthermore - method drawImage is not the part of context's path drawing, so  method isPointInPath (which is using for hit-detecting) wouldn't return true.

Fast workaround - change this line:
https://github.com/openfl/openfl/blob/b69abae749e09b4617c7bc73126cca1ac10e98bc/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L736

with this one:
`if (bitmapFill != null && !hitTesting) {`

**Comment by RealyUniqueName** [comment]
That's not an option, because issue was discovered by a user of third-party openfl-dependent library. 
It's wierd to ask library users to modify their openfl installation )

**Comment by mayakwd** [comment]
I'm agree with you. I can create a pull request, but I'm not sure that my suggestion is right, may be there is a some better solution.

**Comment by jgranick** [comment]
Exactly, if you test and this resolves your issue, we can pull the change in and make it official, but only if we are sure that this really solves the problem

**Comment by mayakwd** [comment]
I've tested fix and it works like a charm :-)

**Comment by RealyUniqueName** [comment]
Thanks!
