### ISSUE TITLE
"Clean up some dynamics" fallout?

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/openfl#1341]
the commit changed 
public var focusRect:Dynamic;;
to
public var focusRect:Null<Bool>;

Now, when in my code, I use
#if flash
        focusRect = new Rectangle();
I get 
        Rectangle should be Null<Bool>

not sure if this is correct?

**Comment by jgranick** [comment]
The documentation says "It can take one of three values: true, false, or null", so it seemed that `Null<Bool>` was the appropriate Haxe type -- AS3 can't support this without being an `Object`

http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/InteractiveObject.html#focusRect

What happens when you set it to a rectangle? Does it behave like `true`?
