### ISSUE TITLE
Tizen Support

### ISSUE THREAD

**Issue by andrew-git** [openfl/openfl#1344]
First of all thanks for such great framework!
What current status of Tizen support and any chance to get lastest SDK support?

**Comment by jgranick** [comment]
I helped explain what happened to our Tizen support [here](http://community.openfl.org/t/tizen-target-dropped/6858/2).

I would love to see Tizen support again, but I'm personally limited in how much energy I can give to it. At the Samsung Developer Conference in April, I talked to developers of the Tizen SDK. They apologized for the (fundamental) API change going to Tizen 2.3, and I encouraged them to support SDL 2 on Tizen.

If there is Tizen support in SDL 2, then it would be simple for us to support. Otherwise, it would be a custom backend that we would could host, but could not spend much time developing

Is there a market for Tizen outside of India? 

:smile: thanks

**Comment by andrew-git** [comment]
Thanks for reply Joshua!

I don't know about market, but Tizen start incentive program http://incentive.tizenstore.com/ and would be great to try it, using habitual tools.
Maybe in view of that they could support updating target in OpenFL to API 2.4?

> The target devices should be Samsung Z1, Samsung Z2, Samsung Z3 and further smart phones launch in the 2017.
Is it possible to build for this device using v2.2 from OpenFL, or it quite obsolete?

**Comment by jgranick** [comment]
Perhaps we can do something with HTML5 + WebGL? That would limit the investment, but still cross the finish line with a suitable working application :smile:

**Comment by jgranick** [comment]
https://trello.com/c/Ch6hlWMm/43-add-tizen-support-using-html5-output
