### ISSUE TITLE
Building from another machine with different OS via (local network connection/ssh) to test/build?

### ISSUE THREAD

**Issue by alexandervrs** [openfl/openfl#1388]
Is there a way to do a `openfl run/build mac` `openfl run/build linux` from a Windows machine (or any other OS that supports lime anyway)?

I am trying to quickly test an openfl app from my Windows machine to my other two which have Mac OSX and Ubuntu respectively. I'd like to be able to both test and build without having to move my toolset/code over to the other OS. I expected some commandline flags to setup local connection ip/username/password etc. to fire up the vm/compiler to the target machine but seems that is not available.

Only workaround I see, is perhaps install haxe & openfl on the target machine and then connect with SSH from Windows to copy files over and build/test them there.

**Comment by jerobarraco** [comment]
i'm not an openfl dev.
it probably would be better to have cross-compiling capabilities but that would be a PIA.
you might also try
on linux
`apt-get install openssh-server`
on winblows
`ssh user@ip "openfl build linux"`

though i recommend you to automate with a bash script instead of running openfl directly.
also you can configure the linux box to mount your sources from winblows and compile from them, though unrecommended.
i had a script that does a git pull then compiles.
i think the same is achievable on mac, but i have no experience there.

**Comment by jgranick** [comment]
Happy to discuss it more here:

https://github.com/openfl/openfl/issues/1396

:smile:
