### ISSUE TITLE
Event.DEACTIVATE & Event.ACTIVATE firing twice

### ISSUE THREAD

**Issue by pozirk** [openfl/openfl#1578]
Hello!
Even with simple example, it fires twice at least on Flash target, didn't test on others.
Latest Lime and OpenFL.

```haxe
class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg");
		
		Lib.current.stage.addEventListener(Event.DEACTIVATE, onDeactivate);
		Lib.current.stage.addEventListener(Event.ACTIVATE, onActivate);
	}

	private function onDeactivate(e:Event):Void
	{
		trace("deact");
	}
	
	private function onActivate(e:Event):Void
	{
		trace("act");
	}
}
```

Results:
> Main.hx:27: deact
> Main.hx:27: deact
> Main.hx:32: act
> Main.hx:32: act
> Main.hx:27: deact
> Main.hx:27: deact
> Main.hx:32: act
> Main.hx:32: act
> Main.hx:27: deact
> Main.hx:27: deact

Could you please fix this?
Thank you!

**Comment by CreativeMagic** [comment]
This is an interesting issue, I'll investigate the cause of this behaviour.

**Comment by CreativeMagic** [comment]
I've tested this on

- Flash
- Neko (win)
- HTML5 (chrome on Win)
- Windows 10

The events worked as expected.

>haxelib list
actuate: [1.8.7]
format: 3.2.1 [3.3.0]
haxelib: [3.3.0]
haxelib_client: [3.2.0-rc.3]
hxcpp: 3.2.102 [3.4.185] 3.4.64
lime-samples: 2.6.0 3.4.0 4.0.0 [4.0.1]
lime: [5.5.0]
moon-core: 1.0.0 1.1.0 [1.1.1]
nape: [2.0.20]
openfl-samples:  [6.0.0]
openfl: [6.1.2]
screenManager: [1.0.0]
swf: [2.3.1]
systools: [1.1.0]


However, if you do see this, try updating your Flash SDK.
Also, not saying your issue is not important, but it seems that Flash will be officially unsupported from year 2020; but that's just a side-note.

**Comment by ROBERT-MCDOWELL** [comment]
> Also, not saying your issue is not important, but it seems that Flash will be officially unsupported from year 2020
let's first debunk this announcement:
- the guy who wrote one article about it is part of chrome team, on behalf of Adobe (WTF?)
- adobe stopped to update flash player on linux in 2010 and they restarted to maintain it this year.
- Zillions of websites, companies and co are using flash player everyday in their activities and for sure they won't invest zillions to convert in another language.
Morality, don't take every word of US corporations as prophet wish.

**Comment by pozirk** [comment]
Issue is 4 months old, I guess it was fixed somewhere on a way.
Anyway, thank you for verifying it @CreativeMagic.

**Comment by pozirk** [comment]
Problem returned.
I'm getting Event.DEACTIVATE & Event.ACTIVATE twice on Flash target.
I've also tested with Neko, and it doesn't has such problem.

**Comment by jgranick** [comment]
We don't have any control over this behavior in Flash Player. Perhaps it's a difference between two Flash Player versions?

**Comment by jgranick** [comment]
It looks like it might also have something to do with how Flash Player is embedded?

https://forums.creativecow.net/docs/forums/post.php?forumid=190&postid=869266&univpostid=869266&pview=t

**Comment by pozirk** [comment]
Ok, then, I'll filter out second event myself.
Thank you!
