### ISSUE TITLE
HTTPStatusEvent.HTTP_STATUS doesn't dispatch anymore with URLLoader

### ISSUE THREAD

**Issue by zatarus** [openfl/openfl#1614]
Is there something recently changed? I had this working in `openfl 4.4.1` and `lime 3.4.1`. After major upgrade to latest version, now if I get a 500 error where IO_ERROR gets fired instead and only `e.text` has the status code. Also, neither "200" or "403" dispatches `HTTPStatusEvent.HTTP_STATUS`
Version dump:
hxcpp: [3.2.94]
lime: [5.1.0]
openfl: [5.1.3]
Safari 10
Firefox 53

**Comment by jgranick** [comment]
We made major changes to the internals of `URLLoader` in order to keep the network code all in the same place, improve support for certain important features, and make OpenFL more consistent across platforms.

I'm sorry that `HTTPStatusEvent` is no longer dispatched -- this was an oversight!

I believe it appears to be working now, with the changes I have made now to the OpenFL repository. You can give these changes a try by changing your local install, or it will go out in the next release :smile:

**Comment by zatarus** [comment]
I appreciate the update, I will try in day and let you know! Thank you.

**Comment by zatarus** [comment]
Hello, we started experimenting with `5.1.5` release which includes the update. Everything looks stable for now, I will let you know if anything goes wrong with HTTP events. Cheers.
