### ISSUE TITLE
Masks are no longer added as children

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#1710]
Original post: http://community.openfl.org/t/openfl-6-1-0-bug-cant-get-frame-maske-object-html5/9517

**Comment by 22Round** [comment]
@jgranick when do you plan to fix this bug? for this I can't port my project from 5.1.5 to 6 version

**Comment by mastef** [comment]
I think the issue here is that layers with a `clipDepth` are suddenly running through the `__render*()` methods, although they are masks. They should only run through `__render*Mask()` methods.

Also masks might have now masks applied to them.

If `clipDepth > 0` we need to save that the MC is a mask, and not render it in `__renderCairo()`, `__renderCanvas()`, `__renderDOM()`, `__renderGL()`.
Only render it in `__renderCairoMask()`, `__renderCanvasMask()`, `__renderDOMMask()`, `__renderGLMask()`, etc.

In our branch we're saving it to a prop in `MovieClip.hx` : 
```
	if(frameObject.clipDepth > 0) {
		displayObject.isTimelineMask = true;
	}
```

And I'm testing now with this change in `DisplayObject.hx` : 
```
	private function __renderCanvas (renderSession:RenderSession):Void {

		if(isTimelineMask || __isMask) return;
```

**Comment by jgranick** [comment]
Would it work to just set `__isMask`?

**Comment by mastef** [comment]
Yeah probably, although I don't see `__isMask` being set, just being unset if `isTimelineMask` was false. I guess it's used to unset non-masks that were added as masks - @lylecox do you remember?

The change happened here ( these are are from the wildworks PR ) : 
https://github.com/openfl/openfl/pull/1815/commits/34f7ef570be917996b984296ed3c8ad8e73a04b1 & https://github.com/openfl/openfl/pull/1815/commits/3ed9a2c5b6effb94dd77df8a17f356ec6ddfa406

```haxe
	if(!__mask.isTimelineMask) {
		__mask.__isMask = false;
	}
```

**Comment by lylecox** [comment]
The problem I fixed was since masks were not being added into __children the ordering ended up wrong and they were not being applied correctly.  I'm not fully versed in how __isMask is used, so your judgement on what to do there would be best. If I remember correctly any changes I made that happened outside MovieClip were to preserve functionality of existing code. The full intent of my changes was to make sure masks were applied to the objects they were supposed to which was achieved by adding them to and keeping them in the correct order within __children.

@sbijoshj created some masking tests we can test any changes on. They were all working when my changes were finished.
