### ISSUE TITLE
Pixelation with masks and WebGL

### ISSUE THREAD

**Issue by danielmar** [openfl/openfl#1804]
Heya,
Here are two bitmaps with a circle mask, both with smoothing set to true

WebGL: (and also native)
![screen shot 2018-01-14 at 15 55 51](https://user-images.githubusercontent.com/2474262/34916599-acba83f8-f943-11e7-9d00-2b85b3a4c66f.png)

Canvas: (-d canvas)
![screen shot 2018-01-14 at 15 55 35](https://user-images.githubusercontent.com/2474262/34916607-bb707790-f943-11e7-8627-721ed6ab0413.png)

The first image shows worse pixelation around the masked area of profile images.
Tested with OpenFL 6.5.0, Lime 5.8.2

**Comment by jgranick** [comment]
We have stencil masks in OpenGL, now, which means we can mask circles and complex shapes instead of only rectangles, but stencil masks are also strict on/off per pixel, and don't include smoothing. Long-term, I want to add support for `cacheAsBitmap = true` alpha-blended masking (which requires a shader change), but that hasn't happened yet. In the meantime, you can either use `cacheAsBitmap = true` on the objects to force canvas rendering on these objects, or another solution I've used before is to move the line border _above_ the masked image, so that the smooth render of the shape covers the image's rough edges

**Comment by danielmar** [comment]
Thanks, i'll try those workarounds!
