### ISSUE TITLE
JS scoping issue

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#1838]
I'm getting the following error in openfl.display3D.textures.VideoTexture when trying to play video via Starling when targetting html5:

`Uncaught TypeError: _gthis.__textureReady is not a function`

It seems like the scope for 'this' is messed up and instead of this referencing the VideoTexture class it is referencing the attachNetStream function. Any idea on what might be causing this? is it an OpenFL problem, or at a Haxe level? I'm not really sure how to work around this :/

This issue is present in the Starling demo video scene

**Comment by jgranick** [comment]
Fixed!

My guess is that passing a closure preserves the scope, for example, consider the following:

```
private function callMethod (method:Dynamic):Void {
    Reflect.callMethod (method, method, []);
}
...
callMethod (myMethod);
```

In JavaScript, I think this behaves similar to:

```haxe
callMethod (myMethod.bind ());
```

...as a result, the scope of `this` is preserved within the function that is passed, so even though the scope when the method is called is the method, not the class, it works fine because the closure is wrapped to preserve scope.

However, code in Starling here was using `Reflect.field` first:

```haxe
var method = Reflect.field(base, "attach" + type);
Reflect.callMethod(method, method, [attachment]);
```

...this was passing the vanilla `attachNetStream` method to `Reflect.callMethod`, which has no guards to protect its scope. The fix was to use `base` as the scope when calling the method.

Tricky :smile:

**Comment by peteshand** [comment]
Hey Joshua. Thanks for looking into this, really appreciate it!
I really don't get js scoping, it seems super unhelpful.
