### ISSUE TITLE
Apparently some IIS servers block .bin files

### ISSUE THREAD

**Issue by kasparsj** [openfl/openfl#1860]
So you get 404 for them.
Is this a good enough reason to change the extension, or maybe provide a way to configure it?

**Comment by jgranick** [comment]
There is a `-Dforce_dat_suffix` define, which uses `.dat` instead of `.bin`, but it would be nice to make this configurable in the future, or possibly we could use JSON or something instead. I'll close this issue for new, and we can leave the door open for pull requests / enhancements in the future as needed
