### ISSUE TITLE
font from haxelib lib is included wrong

### ISSUE THREAD

**Issue by Marc010** [openfl/openfl#189]
See: https://github.com/HaxePunk/HaxePunk/issues/221 (last 2 comments)

On windows openfl includes the full path to a font when embedding it.

**Comment by jgranick** [comment]
Appears to be fixed, I think the issue is making certain that the asset path is included in the _classpath_ (not asset path, as a Haxe macro embed is a Haxe, not asset, function -- not sure if we should add asset paths to classpaths by default to handle that?), and then using the `Context.resolvePath` method in the Macro to help resolve based on all available classpaths when searching for an asset. Thanks!
