### ISSUE TITLE
Socket not working on BB10?

### ISSUE THREAD

**Issue by stahlratte** [openfl/openfl#194]
Steps to reproduce:

1. Create openfl project with Flashdevelop.
2. instantiate a sys.net.Socket
3. run on blackberry device

Application will close immediately.

Another example would be to create a customRequest with haxe.Http. That's what I'm trying right now, because PUT is not implemented in the flash api.
I narrowed it down to the Socket.
I really would like to see the socket working on BB10.

thx,
rudi

**Comment by jgranick** [comment]
I have a feeling that this may have been resolved when I fixed BlackBerry 10.3 support, there was an issue with socket, specifically, where it was not linking a system library it needed. Instead of blowing up at runtime (as you've experienced) it would blow up when trying to run the project. Adding the missing reference may well have been the issue that was occuring here
