### ISSUE TITLE
BitmapData.loadFromFile freezes the app on Linux when loading a corrupted PNG file

### ISSUE THREAD

**Issue by miriti** [openfl/openfl#1999]
It works absolutely fine with any other files except for[ this one](https://raw.githubusercontent.com/miriti/openfl-corrupt-png-bug/master/Assets/corrupt.png). This file is corrupted. I'm not sure how exactly. Some tools open this file just fine, others report corruption.

The problem is that BitmapData.loadFromFile just hangs while trying to load this file. onError callback never being called and try/catch doesn't work either. The only way to stop the programm is to kill it with SIGKILL. It happenes on both Neko and Linux targets.

It doesn't happen on MacOS. I didn't try it on Windows just yet.

Synchronous BitmapData.fromFile works just fine (it doesn't load the file but try/catch catches an error).

OpenFL version: 8.4.1-LlyE3A
Lime version: 7.0.0
hxcpp version: 4.0.4
OS: Arch Linux amd64

[MCVE](https://github.com/miriti/openfl-corrupt-png-bug)

**Comment by jgranick** [comment]
Thank you so much for the example file!

We were not handling errors in libpng the same way when loading from bytes (which occurs in the async version) as we were when loading from disk.

In the process, I improved how the `fromBytes` and `fromFile` work so that they return `null` and an error on async, then OpenFL's side so it also does not return a `BitmapData` if the load failed.

Now `BitmapData.fromFile` should return null when it fails and `BitmapData.loadFromFile` should error
