### ISSUE TITLE
OpenFL 8.5.0 spamming context3d calls

### ISSUE THREAD

**Issue by peteshand** [openfl/openfl#2017]
Hey I've just noticed that after updating to OpenFL 8.5.0 there are a tonne of unwanted calls to context3D. For some context I have a 2d framework built on top of OpenFLs stage3D implementation and after the update it no longer renders anything to screen while targeting HTML5 (Flash/AIR still work correctly).

Is there a way to disable OpenFLs calls to Context3D while still using the Stage3D API? I can see there is a compile flag "openfl_disable_display_render", however enabling this seems to completely stop all Stage3D calls regardless of if they are from OpenFL itself or external calls.

OpenFL 8.4.1 Context3D Calls
![alt text](http://peteshand.net/downloads/openfl_8.4.1.png "OpenFL 8.4.1 context3D calls")

OpenFL 8.5.0 Context3D Calls
![alt text](http://peteshand.net/downloads/openfl_8.5.0b.png "OpenFL 8.5.0 context3D calls")

OpenFL 8.5.0 Context3D Calls with openfl_disable_display_render flag
![alt text](http://peteshand.net/downloads/openfl_8.5.0_openfl_disable_display_render.png "OpenFL 8.5.0 context3D calls")

FYI, I'm using the chrome extension "WebGL-Inspector" for context call inspection
http://benvanik.github.io/WebGL-Inspector/

**Comment by jgranick** [comment]
OpenFL has a new `Context3D` and an updated display list renderer for hardware targets.

The display list renderer uses `Context3D` for all its rendering, but it (by default) uses a _separate_ `Context3D` instance. `stage.stage3Ds` now supports 2-4 `Stage3D` instances (whether mobile or desktop) and will give their own framebuffer so that they can `present()` as often (or rarely) as desired, and to prevent conflicts between the core display list renderer stencil/depth buffer and other `Stage3D` renderers.

You will need to request a context (like on Flash) and will now need to call `present()` for anything to show. Please take a look and see if any of these changes need to be made for your framework to work

**Comment by peteshand** [comment]
Yep my framework currently handles .clear .drawTriangles .present etc. I'll keep digging over the next few days, but it appears there is different behaviour between HTML5 and AIR.. in an ideal world they should really behaviour the same correct?

**Comment by peteshand** [comment]
Hey Joshua

Thanks for the tips.

Adding the openfl-share-context flag seems to resolve the issue.. I would like to get it working within the flag so I'll continue looking for the root cause over the weekend.

Note: 8.5.0 and 8.5.1 behave the same, so it's likely not related to stencil buffers

**Comment by peteshand** [comment]
Hmm question, what does the openfl-share-context flag actually do? I can't find any `#if openfl-share-context` within the openfl source code

**Comment by peteshand** [comment]
Hello triangle 8.4.1
http://peteshand.net/downloads/openfl/hello-triangle/8.4.1/

Hello triangle 8.5.1
http://peteshand.net/downloads/openfl/hello-triangle/8.5.1/

**Comment by jgranick** [comment]
Thanks, I'll take a look

**Comment by jgranick** [comment]
`setVertexBufferAt` and `setProgramConstantsFromMatrix` are not properly cached between Stage3D instances, if the shader program changes (on any `Stage3D` instance) then these are cleared. It's a more complicated issue to resolve. I've opened a new issue to track it: https://github.com/openfl/openfl/issues/2018
