### ISSUE TITLE
keycode to charcode seems rock n' roll

### ISSUE THREAD

**Issue by delahee** [openfl/openfl#2146]
Hey :)

Right now charcode to keycode translation seems a bit rock n' rollish, on my french (fr-fr) keyboard under windows, keys are very divergent from flash... and from printed buttons.

Just a wide question, is there any library or specific process to adjust or is there room for adjustment? Maybe an SDL thing?

I'll just make a tiny layer of indirection right now but if you have thoughts, I am widely interested :)

Thanks!

**Comment by delahee** [comment]
It seems the keyLocation is often empty which for example forbids 'à' to be distinguished from ')' which is inconvenient for some use schemes.

I'll wait for an update on the correct approach :)
Thank you very much

**Comment by jgranick** [comment]
We use SDL for keyboard input on native platforms.

SDL provides two APIs for keyboard events -- key codes and scan codes. One is meant to be based on the physical key location, the other is meant to be the logical value of the key.

I believe we use the key codes, currently, but this could change if other keyboards could be better supported otherwise. I believe we currently hard-code translation from Lime key codes to OpenFL key values to mirror Flash's behavior, but outside of QWERTY this is probably unreliable.

I think we don't have a way of knowing the keyboard layout, but perhaps with some attention, it would be possible for us to better support more types

**Comment by delahee** [comment]
Thanks for the linked code, very interesting.

hmmm ok I think the calculus is misleading on non qwerty stuff.  That is probably what masks my keys.
var charCode = Keyboard.__getCharCode(keyCode, modifier.shiftKey);
shoud be 
var charCode = Keyboard.__getCharCode(keyCode, modifier.shiftKey,modifier.altGrKey); 
for exotic keyboard like french

Ok thanks, I'll dig a bit about whether SDL have code translation stuff and get back to you with some more actionnable stuff if needed or PR.

I'll close for now to avoid pollution.

**Comment by delahee** [comment]
Maybe we could use :

https://wiki.libsdl.org/SDL_GetKeyName?highlight=%28%5CbCategoryKeyboard%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29

I don't see it referenced here : 

https://github.com/openfl/lime/blob/78e99bf1d92266a06605e32147c9c6ba3a6a03dc/project/src/backend/sdl/SDLKeyCode.cpp

( sorry I don't still get the whole SDL-openfl infrastructure yet. )
We could avoid an allocation by blitting the UTF8 "name" in a full 32-bit "charcode" ?
What do you think ?

Thanks a lot for reading.
