### ISSUE TITLE
openfl process error - Invalid field access : length

### ISSUE THREAD

**Issue by djmuted** [openfl/openfl#2200]
I am trying to process a SWF file to use with OpenFL. All my AS2 SWFs worked fine, but when I tried to convert this example AS3 file (https://icer.ink/media1.clubpenguin.com/play/v2/client/puffle/care/assetLibraryBlue.swf) I get 
```
>openfl process assetLibraryBlue.swf blue.bundle
Called from ? line 1
Called from Tools.hx line 617
Called from Tools.hx line 648
Called from format/swf/exporters/SWFLiteExporter.hx line 62
Called from format/swf/exporters/SWFLiteExporter.hx line 99
Called from format/swf/exporters/SWFLiteExporter.hx line 915
Uncaught exception - Invalid field access : length
```
There should be an option to use **openfl process** command without generating scripts for it , but I couldn't find one.

**Comment by djmuted** [comment]
Just checked and this issue seems to be fixed in the git master version of openfl.

**Comment by jgranick** [comment]
We are creating a new intermediate format and changes to the runtime code for SWF-based assets -- in GIT the `openfl process` command uses this new format which may have some issues of its own but I think it will be quite promising

Would you be interested in sharing SWFs we could use to test the quality and performance of the new format?

**Comment by djmuted** [comment]
Yes, of course!
Current stable OpenFL version has some issues with rendering in low quality and missing some shapes in more complex SWFs. 
An example could be seen here: https://icer.ink/media1.clubpenguin.com/play/v2/content/global/rooms/dock.swf
you can also test using any other SWFs in this directory (the listing is enabled)
https://icer.ink/media1.clubpenguin.com/play/v2/content/global/rooms
A small comparison:
![Adobe Flash vs OpenFL](https://i.imgur.com/kaxRtRg.png)

**Comment by jgranick** [comment]
Ah! Yes

That looks like the "seams" issue caused by how canvas and cairo handle smoothing:

https://stackoverflow.com/questions/19319963/how-to-avoid-seams-between-filled-areas-in-canvas

I noticed that HTML5 canvas exports from Adobe Animate also have this problem :sweat:

Another goal we have with the new format is to make it so the Flash target uses the same format as other targets so that we can isolate issues related to the SWF conversion or related to how OpenFL and Flash Player have different renderer implementations.
