### ISSUE TITLE
Output of BitmapData.draw() is inconsistent among targets

### ISSUE THREAD

**Issue by kevinresol** [openfl/openfl#221]
Refer to this forum post:
http://www.openfl.org/forums/#!/bugs:bitmapdatadraw-with-smoo

**Comment by larsiusprime** [comment]
This issue seems still present in the new release ("next").

I am using the latest lime/openFL dev versions from github from the openfl repo, on the master branch.

Here's the results I'm getting on my test project (source and assets provided at bottom of post):

Flash: (correct)
![flash](https://cloud.githubusercontent.com/assets/739064/7055528/b5c4c3bc-de09-11e4-8891-d30d7c078fbe.jpg)

Cpp/Neko: (partly correct, partly incorrect)
![cppneko](https://cloud.githubusercontent.com/assets/739064/7055542/cd74f496-de09-11e4-990d-12618fa6d325.jpg)

HTML5: (incorrect)
![html5](https://cloud.githubusercontent.com/assets/739064/7055545/d291e6aa-de09-11e4-9156-3be1bea20120.jpg)

Here is the code that generates this:
```haxe
package;


import openfl.display.Bitmap;
import openfl.display.BitmapData;
import openfl.display.Sprite;
import openfl.Assets;


class Main extends Sprite {
	
	public function new () {
		
		super ();
		
		openfl.Lib.current.stage.color = 0xFF808080;
		
		var bchar = Assets.getBitmapData("assets/object.png");
		var blit = Assets.getBitmapData("assets/light.png");
		
		var char = new Bitmap(bchar);
		var light = new Bitmap(blit);
		
		light.alpha = 0.5;
		light.blendMode = openfl.display.BlendMode.MULTIPLY;
		
		addChild(char);
		addChild(light);
		
		var bmp2:BitmapData = bchar.clone();
		bmp2.draw(blit, null, new openfl.geom.ColorTransform(1,1,1,0.5), openfl.display.BlendMode.MULTIPLY);
		
		var char2 = new Bitmap(bmp2);
		char2.x = char.width;
		
		addChild(char2);
	}
}
```

And here are the asset files used:

object.png:
![object](https://cloud.githubusercontent.com/assets/739064/7055557/ea56771a-de09-11e4-9dfa-8bb071fd6db2.png)

light.png:
![light](https://cloud.githubusercontent.com/assets/739064/7055554/e7731260-de09-11e4-8ce0-c31c5d1f06a4.png)

**Comment by larsiusprime** [comment]
From what I can surmise:

1. Flash: handles blending correctly on the display list and in BitmapData.draw()
2. CPP/Neko: handles blending correctly on the display list, ignores blend/colorTransform in BitmapData.draw()
3. HTML5: handles alpha but not blending on the display list, ignores blend/colorTransform in BitmapData.draw() -- and also doesn't update the stage's color at runtime.

**Comment by mrcdk** [comment]
Ok, made a PR for webGL, it should work now.

**Comment by larsiusprime** [comment]
I just tested, and flash, cpp, and neko work correctly now, but HTML5 does not.

By default it launches in firefox, let me try chrome.

Yup, same results in both. It still looks exactly like the HTML5 screenshot above. It is possible my browsers aren't using WebGL for some reason?
