### ISSUE TITLE
Stretch goal: Automate OpenFL release builds using Github Actions

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl#2388]
It would be great if we could automate the final build/packaging of OpenFL with Github Actions and so avoid the private TeamCity server

**Comment by nanjizal** [comment]
I would like builds to be sporned from Haxe nightly builds, because I think this may allow better integration and flagging of issues earlier. Simple problems could be patched easier, larger ones could be flagged with Haxe compiler dev's early. 

For instance if they make a change that seriously cripples OpenFL then a request could be made quickly to revert till better support was provided.  Haxe toolkits are like the Rails of Haxe thier stability needs to be treated more seriously by the core team.

Hxcpp need these actions as well, to create a consistant approach otherwise 1 part out of 3 is missing?

**Comment by jgranick** [comment]
The issue with doing unit tests on each new Haxe develop release is that we may have "false positives" where it reports that OpenFL is broken when actually Haxe is broken or has changed an API. Integration tests with both make sense but I'm not sure what the right context would be
