### ISSUE TITLE
Error when rendering static text fields processed by SWF lib

### ISSUE THREAD

**Issue by twilson90** [openfl/openfl#2586]
**Describe the bug**

I'm trying to process an SWF that includes static text fields, but I keep getting these 2 errors:
src/swf/SWFTimelineContainer.hx:258: WARNING: excess bytes: 2, Tag: DefineFont3, Index: 130
src/swf/SWFTimelineContainer.hx:258: WARNING: excess bytes: 2, Tag: DefineFont3, Index: 1684

When I try loading the processed SWF asset and displaying it in OpenFl it works, it renders the static text correctly...

However if I then try my own 'render' with `BitmapData.draw(asset_mc_with_static_text)` I get this error in CairoRenderer.hx ln 196:

`Can't cast openfl.text.StaticText to openfl.display...`

If I remove all instances of static text it works correctly.

**OpenFL Targets**
Hashlink

**Additional context**

**Comment by joshtynjala** [comment]
So it looks like `StaticText` extends `DisplayObject` and sets `__drawableType = SHAPE`.

`CairoRenderer` calls `CairoShape.renderDrawable(cast object, this);` for the `SHAPE` type. `CairoShape.renderDrawable` expects the first argument to be of type `Shape` instead of `DisplayObject`.

If I look at `OpenGLRenderer` instead, it calls `Context3DDisplayObject.renderDrawable` for the `SHAPE` type instead of `Context3DShape.renderDrawable`. `Context3DDisplayObject` then checks if `__graphics` is defined and calls `Context3DShape.renderDrawable`.

Similarly, `CanvasRenderer` calls `CanvasDisplayObject.renderDrawable` for the `SHAPE` type.

It looks like one of three things needs to change:

1) `StaticText` should use a different `__drawableType`
2) `StaticText` should extend `Shape` instead of `DisplayObject`
3) `CairoRenderer` should call `CairoDisplayObject.renderDrawable` instead of `CairoShape.renderDrawable` when `__drawableType == SHAPE`

Since `OpenGLRenderer` and `CanvasRenderer` both seem to follow 3 already, I think that 3 is the correct solution.
