### ISSUE TITLE
[HTML5] Display looks bad when it is not a scale

### ISSUE THREAD

**Issue by utaner** [openfl/openfl#2677]
**Describe the bug**
Display looks bad when it is not a scale.

**Disable Windows Scaling**

![image](https://github.com/openfl/openfl/assets/24855850/fb7eff49-ffe7-4742-82a6-c0cb29c04cee)

You need to select 100% for disabling windows scaling

**To Reproduce**
1. Disable Windows scaling as this issue only works when the `window.devicePixelRatio` value is 1.
2. Install openfl-animate-atlas with `haxelib git openfl-animate-atlas https://github.com/barisyild/openfl-animate-atlas`
3. Download and extract [quality_issue.zip](https://github.com/openfl/openfl/files/13625165/quality_issue.zip)
4. Build project with `lime test html5` or `openfl test html5`
5. See error

**Expected behavior**
Display must be smooth.

**Screenshots**
With Windows Scaling
![image](https://github.com/openfl/openfl/assets/24855850/c52cc516-da2c-4876-8e54-e4127e70d438)

Without Windows Scaling
![image](https://github.com/openfl/openfl/assets/24855850/25647a43-8ad9-4a35-a601-821fb39a1e6b)

**OpenFL Targets**
OpenFL 9.3.2
Lime 8.1.1
HTML5

**Addtional Context**

If you zoom the page when opening the application and then return it to normal, `window.devicePixelRatio` value will not be 1 when opening the application, so the image will be sharp.

**Comment by joshtynjala** [comment]
Copying my response from the Discord. Maybe it'll be useful to someone else too, if this thread shows up in a Google search.

From your project.xml file:

> `<window width="1024" height="768"/>`

When you set the `<window>` width and height to something lower than the browser window dimensions for the html5 target, a lower rendering quality is expected with our default index.html template because that template still makes the canvas fill the entire browser view port. In other words, it is scaled up from a lower resolution. It should be a little blurry.

When you bump up scaling outside of OpenFL, the browser's `window.devicePixelRatio` is increased. That's the value OpenFL uses to determine how much it should scale itself for HiDPI screens. So OpenFL is rendering at higher quality than it normally would for the window dimensions that you specified (but closer to what it would be if you had specified no window dimensions at all). Since the canvas still fills the same amount of space in the browser window, it ends up looking crisper.

Both behaviors are expected when you specify window dimensions in project.xml for the html5 target.
