### ISSUE TITLE
manageCookies does not withCredentials in HTTPRequest

### ISSUE THREAD

**Issue by rat-moonshine** [openfl/openfl#2719]
**Describe the bug**

Based on an old request ([URLLoader should expose requests withCredentials for html5](https://github.com/openfl/openfl/issues/934)) another trailing [issue](https://github.com/openfl/openfl/pull/956#issuecomment-337709332) suggested that using `URLRequest.manageCookies` is now suppose to work for `HTTPRequest.withCredentials`:

> Since we added official Adobe AIR support, it opened up a good way for us to support urlRequest.manageCookies (doing withCredentials under the hood) as a real property on most targets, and a dummy property on Flash Player

In current `URLLoader` [codes](https://github.com/openfl/openfl/blob/develop/src/openfl/net/URLLoader.hx#L395-L397) - it sets `__httpRequest.manageCookies = request.manageCookies`; I failed to found any relation between `manageCookies` and `withCreddentials` in current codes, though. 

Our application fails to send cookies over a CORS request by just setting `URLRequest.manageCookies=true`, unless we manually edit `URLLoader` class to access its _request_ and sets its `withCredentaials` property to _true_.

**Requirement**
Either one of the following:
- Ensure that `request.manageCookies` properly updates `httpRequest.withCredentials`
- Provide a way to set this on `URLLoader` level (however, it feels the former would be more acceptable)

**Additional context**
Lime: GitHub (develop)
OpenFL: GitHub - 9.4.0-Dev
Haxe: 4.3.4
Windows: 10
Browsers: Mozilla, Edge

**Comment by dimensionscape** [comment]
I do not think marrying `UrlRequest.manageCookies` to  `HttpRequest.withCredentials` is appropriate as they are two distinct concepts. ~In AIR, iirc, this is handled through the `URLRequest.authenticate` property, which is true by default, and currently not available in OpenFL.~

**Comment by rat-moonshine** [comment]
My impression was only build upon the [comment](https://github.com/openfl/openfl/pull/956#issuecomment-337709332) that marked this fixed. It's an old comment, so possible many things have changed by then.

For now, we overcome the problem by accessing URLLoader's `HTTPRequest.withCredentials` and makes it _true_. It would be intuitive if some way we access/set this property by URLLoader, easily.

**Comment by dimensionscape** [comment]
I could be wrong, but I believe there was a mistake in the wording of that response by @jgranick at the time. Instead, `withCredentials` was added to the *Lime* api here: https://github.com/openfl/lime/commit/9afbdbe586ef23166c1a97f2c65dca4b54d787f2

**Comment by joshtynjala** [comment]
It actually was not a mistake in wording. In a previous version of OpenFL, `urlRequest.manageCookies` was indeed passed to Lime's `httpRequest.withCredentials`. However, I changed it a while back because, while the two properties are meant to affect cookie behavior, they're not actually the same. `manageCookies` controls whether cookies are used at all. `withCredentials` specifically applies to cross-origin requests only.

When I changed it, I did not expose a separate way to modify Lime's `withCredentials` when using `URLRequest`. I probably should have. With my latest commit to 9.4.0-Dev, you can now set a new `urlRequest.withCredentials` property, which gets passed to Lime's `HTTPRequest.withCredentials`, and then `XMLHttpRequest.withCredentials`. On other targets, it has no effect, and that's fine because it is similar to how `XMLHttpRequest.withCredentials` doesn't affect same-origin requests (all other targets are effectively always same-origin).

**Comment by rat-moonshine** [comment]
Thank you @joshtynjala . I shall give this a test soon after updating Openfl library. Hopefully, everything will work alright and I won't need to access that property backdoor. Thank you, very much.

**Comment by rat-moonshine** [comment]
> which gets passed to Lime's HTTPRequest.withCredentials, and then XMLHttpRequest.withCredentials.

I'm just curious to know, is `XMLHTTPRequest` works behind `HTTPRequest`, @joshtynjala (?)

**Comment by joshtynjala** [comment]
When targeting HTML5, XMLHttpRequest is used for HTTPRequest.

https://github.com/openfl/lime/blob/8.1.2/src/lime/_internal/backend/html5/HTML5HTTPRequest.hx#L63

When targeting native, it uses cURL.
