### ISSUE TITLE
User-programmable shaders for DisplayObjects/Bitmaps

### ISSUE THREAD

**Issue by TheSHEEEP** [openfl/openfl#303]
As the foundation for this has basically been introduced to lime "next" ( https://github.com/openfl/lime/issues/47 ), it would be great to have a simple to use interface in OpenFL that lets users use their own fragment shaders on a DisplayObject level.
Vertex shaders would be nice, too, but IMO optional as we're mostly talking about 2D here.

I am talking about a level of simplicity like this:

    var shaderEffect :ShaderEffect = new ShaderEffect("assets/shaders/myEffect.frag");
    shaderEffect.awesomeConfigurationOption = true;
    myDisplayObject.shaderEffect = shaderEffect;

I am unsure if this is possible on a DisplayObject level, but it should be possible on a Bitmap level.

**Comment by TheSHEEEP** [comment]
Has any work been done by now that would make implementing shader effects like these easier?

**Comment by larsiusprime** [comment]
Pinging @mrcdk

**Comment by mrcdk** [comment]
https://github.com/openfl/openfl/pull/697

**Comment by larsiusprime** [comment]
There we go :)

**Comment by TheSHEEEP** [comment]
Great to see that!
I hope it can be mergen in eventually :)

**Comment by TheSHEEEP** [comment]
Seems like @mrcdk stopped working on that.
Too bad, it seemed very promising!

**Comment by mrcdk** [comment]
I haven't, it's done. There are a few problems. The first one is that the
whole structure of the lib has changed (at least the parts that my
implementation cares about) so merging it will be a nightmare. The other
problem is that it needs a few fixes that I committed and were reverted
because they were failing in a particular case. I'm waiting for them to be
merged back.

So, once that last problem is solved, I'll see if I have time to make the
PR mergable again.

**Comment by larsiusprime** [comment]
Hey @mrcdk, happy to help facilitate stuff. What are your pain points at the moment? I'm happy to break this down into a series of steps that we can try to push through in the next few weeks and see if Joshua, et al. can help figure it out.

**Comment by jcward** [comment]
FYI, the original #697 was closed, and the reincarnation #874 was merged. Perhaps we should close this issue now?
