### ISSUE TITLE
Package name conflict with HTML5 target

### ISSUE THREAD

**Issue by Masadow** [openfl/openfl#357]
Hey,

I built my app under HaxeFlixel but I'm pretty sure it's openFL related.

So here is my really simple code

```
var pieces = new Array<Piece>();
pieces.push(new Square());
for (piece in pieces) { }
```

In this example, Piece and Square are both located in package piece.

When this code runs, the console produce this error `Uncaught TypeError: Cannot read property 'Square' of undefined`

**Comment by urbananimal** [comment]
Is there any way to disable js-flatten?? If not then enabling it by default seems to me to be a hasty decision. This change could break (has broken) existing code - if you're using external libraries (my situation) for example and also result in confusing errors. Is there any other good reason for enabling this by default? It seems to me to be a rather crude solution to the issue raised, which I imagine is an extremely rare issue that can be very easily circumvented... It is also inconsistent with vanilla haxe where it is optional.

**Comment by jgranick** [comment]
Hey, yeah, it's enabled because I think it may improve performance (`my_long_named_package.Class` is less lookups than `my.long.named.package.Class`) as well as resolving unexpected errors in code when you use variable names that share the same name as part of a package.

Which is the scenario where it is breaking your code? The Haxe code should be inside an enclosure, so it shouldn't really interact with other JS on the page

**Comment by urbananimal** [comment]
Hey, thanks for your response. 
Yeah it might, but one always has the option of enabling that feature and getting that (very small? (depending on circumstance)) performance improvement as you would if you were developing in vanilla Haxe. 
My situation is that I have to integrate with an external library that is not compiled as part of my project but is provided to me as a js file which I concatenate with my js output as part of my build. This change breaks my integration (and it took me an age to figure out why). I can get it to work by hacking the openfl compilation configuration but I'll have to do that with every update. I suppose I could write an extern class or do some funky conditional compilation stuff but those will both be loads more work than hacking the config. Whereas the issue which prompted this change could be circumvented by adding the optional define to ones project config or by putting all packages into another package (com?) or of course it could be fixed by doing some kind of checking/warning/renaming at compile time.

**Comment by jgranick** [comment]
Could you include the additional JS as a separate JS file? Or if it isn't very large, could you use `untyped __js__ ("<code goes here>")` to include it in your Haxe code somewhere?

**Comment by urbananimal** [comment]
I'm not sure what you mean, maybe there is some confusion (I've not been using openfl for very long so it's probably mine). Let me clarify - I have a crossplatform application that I have to integrate with a third party wrapper application. I have a class that implements an interface (well there are several classes and several interfaces) which is a member of the third party library. I have an extern class for this interface. The third party library adds it's class definitions (javascript Objects) to the global name space using normal nested objects (package.package.class) (in the flash version I have an swc that is included in the compilation; this works fine). I include the third party library by concatenating it with the compiled output from my openfl application so I have a js file with two closures (libraryCode)() & (applicationCode)(). My application is trying to access the library classes through package_package_class because of js-flatten but the library has implemented them package.package.class.

The way I see it you would have the same problem if you wanted to include any javascript library, jQuery for example.

If you are saying there is a better or more correct way of including a third party javascript library in a project then that would be great :)

**Comment by jgranick** [comment]
Ah, so it's modifying the calls to your external library code, I see.

In this case, have you tried the `@:native` meta tag? I think you could probably use `@:native("my.library.code.Class")` to prevent the JS-flatten behavior on that extern class you wrote?

**Comment by urbananimal** [comment]
Hey, thanks for helping me out, I appreciate it.

That doesn't work. It seems like it should work but as you can see from the last comment here - https://github.com/HaxeFoundation/haxe/issues/2132 - it doesn't seem to be fixed.

**Comment by jgranick** [comment]
Alright, I've removed the default `-D js-flatten` in the HXML.

People can add this again using `openfl test html5 -Djs-flatten` or `<haxedef name="js-flatten" if="html5" />` in a project XML.

If that is not fixed, then I can't think of a suitable workaround. `@:native` would be the way to go, to work with or without "flatten".

**Comment by urbananimal** [comment]
Great. Thanks for your help :)

**Comment by urbananimal** [comment]
FYI - https://github.com/HaxeFoundation/haxe/issues/2132#issuecomment-69724043

**Comment by jgranick** [comment]
Oh, okay, good. I think I may be adding this flag again, perhaps from the include.xml, and perhaps there will be a way to disable it. I think it lends to cleaner/more consistent output. If it works in 3.1.3, and now is fixed in the repository releases as well, then I think it will work everywhere. `@:native` is the way to make sure it works properly with or without flatten :smile:

**Comment by urbananimal** [comment]
Well, presumably the fix will be in the next release, 3.1.4?

Either way - IMO it should be an optional flag or there should be an optional js-nested flag or something - you should not be restricted to one type of output. :)

**Comment by urbananimal** [comment]
I see you did add this back in to the include.xml. How about adding unless="noFlatten" to that haxedef tag?

**Comment by jgranick** [comment]
I've just decided to change how this is behaving, I remembered that one other thing about it is that it helps minification run better.

Now, I've set the Lime tools to automatically run "minify" on HTML5 "final" builds. You can do this using "openfl test html5 -final"

I have also moved the "js-flatten" behavior into the final.hxml, and added "-dce full" in there as well.

Being a template file, anyone can overwrite the final.hxml file with their own configuration, since it requires an additional flag, the "-final" build is also less commonly used, so this is more of an "opt-in" behavior than always being there by default.

In the "DisplayingABitmap" sample, it drops from 868 KB to 166 KB when doing a "-final" build now. It builds slower, but it's more suitable for release.

Adding the same behavior to the Lime "SimpleImage" sample, it went from 308 KB to 45 KB for a "-final" build.

Eventually, I think we may be able to automate even better results using the ADVANCED compilation mode of the closure compiler, but for now I don't think that is safe.
