### ISSUE TITLE
Small glitches on smoothed bitmap with indexed color bitmapdata.

### ISSUE THREAD

**Issue by Horsetopus** [openfl/openfl#375]
When using a png bitmapdata with indexed colors, setting smooth on a bitmap, and scaling or rotating the bitmap, some black pixels appear 
That's true at least for Windows and Android.

Sample code:
```javascript
    bitmap = new Bitmap( Assets.getBitmapData("img/test.png"), PixelSnapping.AUTO, true );
    bitmap.scaleX = bitmap.scaleY = 0.99;
    addChild( bitmap );
```

Tested picture
![test](https://cloud.githubusercontent.com/assets/2189170/4865340/5d8522c2-6123-11e4-8d23-420f3b168032.png)

Result
![result](https://cloud.githubusercontent.com/assets/2189170/4865344/6543b424-6123-11e4-8252-98f51e7c302d.png)

I know I could just not index colors, but it's a good way to reduce the size of an app.

**Comment by xraven13** [comment]
I am wondering how all games that was released prior this fix avoided this problem because it seems like a really big deal ? In my game sprites sometimes have white glitches around them, sometimes they not ( even the same sprite works / doesn't work randomly ). 
I am using old OpenFL 1.2, is there any way I apply the new fix to it ? Or is it possible to do something else to fix this problem ( without updating to new OpenFL of course ).

**Comment by jgranick** [comment]
As a workaround, you can disable smoothing, or you can modify your source image so that the transparent areas do preserve color. Use a color that's as close to the edges of your image as possible. As a result, when it blends, it will blend the alpha, but will not end up modifying the color, noticeably

**Comment by ibilon** [comment]
Next doesn't have the issue,
and fixing premultiplied alpha on legacy is too much work considering we stopped doing improvements on it.

If next has some issues on your project please report them.
