### ISSUE TITLE
openfl.geom.Transform is missing matrix3D

### ISSUE THREAD

**Issue by Type1J** [openfl/openfl#469]
The matrix3D property is used after an assignment to rotationX, rotationY, or z properties of a openfl.display.DisplayObject.

Note that rotationX, rotationY, rotationZ, and z properies are also missing.

I'm adding this issue because I believe that with OpenFL "next" it may be feasible to add these properties at no additional rendering cost on WebGL and OpenGL.

**Comment by Type1J** [comment]
Needed by HaxeUI https://github.com/ianharrigan/haxeui/issues/211

**Comment by jgranick** [comment]
At the moment (as you know) we do not support rotationX, rotationY, rotationZ or z. These seem to have been "oft" supported within Flash, and I'm not sure whether we will implement them in the renderers.

With these missing, it did not make sense to support a Matrix3D property, but I suppose that there is no good reason why we could not just return a 2D matrix in the Matrix3D property. I will try and take a look

**Comment by sonygod** [comment]
why we could not just return a 2D matrix in the Matrix3D property. I will try and take a look

because there many game as3 code use Matrix3D , current flash platform convert to  h5 only few  tool 

,include  [Layabox,](https://www.layabox.com/?language=en) ,openfl
both not support Matrix3D,it's need rewrite lots of code to fixed originally as3  code .

**Comment by jgranick** [comment]
Current versions should have a working 2D `matrix3D` property?

**Comment by sonygod** [comment]
you can look a game like here,there are lots of code use matrix3D api in 2d.

http://beautifl.net/?id=903

and full source   here 


[as3car.zip](https://github.com/openfl/openfl/files/3088641/as3car.zip)
