### ISSUE TITLE
Multitouch on Mac OS X not capable values

### ISSUE THREAD

**Issue by fzzr-** [openfl/openfl#472]
Using `openfl.ui.Multitouch`
````haxe
trace(Multitouch.inputMode); //             NONE
trace(Multitouch.mapTouchToMouse); //     Class<openfl._v2.ui.Multitouch> has no field mapTouchToMouse
trace(Multitouch.maxTouchPoints); //        2
trace(Multitouch.supportedGestures); //     null
trace(Multitouch.supportsGestureEvents);//  false
trace(Multitouch.supportsTouchEvents);//    false
````

This is not the correct values. Mac OS X supports gestures at least two-finger.

**Comment by jgranick** [comment]
`Multitouch.mapTouchToMouse` is an AIR-only API, at the moment, we're focused on Flash APIs, instead of AIR APIs, I expect that additional functionality will primarily be exposed through Lime

Currently OpenFL does not support gestures, and only provides mouse or touch events. Even though the OS supports gestures, I'm not aware of any gesture event support in SDL. Someone could implement a compatibility library to automatically detect gestures, but at the moment, the above looks correct to me
