### ISSUE TITLE
set_scrollRect, and scroll rectangle + graphics rendering

### ISSUE THREAD

**Issue by ghost** [openfl/openfl#529]
I've noticed a couple of issues while using DisplayObject's scrollRect propterty.
The following code does not have the same behavior on openfl next and flash targets.
```
var s = new Sprite();
s.scrollRect = new Rectangle(0, 0, 200, 200);
var r = s.scrollRect;
r.x += 15;
s.scrollRect = r;
```
On flash, this code shifts the scroll rectangle over by 15 pixels. But on openfl next targets, this code does not effect the sprite until it is marked as dirty again. In openfl/display/DisplayObject.hx, on line 1515 in set_scrollRect(), should the if statement be removed so that __setTransformDirty() is always called?

(is this next issue an issue with lime?)
The following code does not have the same appearance on openfl next and flash targets.
```
var s = new Sprite();
s.graphics.beginFill(0xFF0000);
s.graphics.drawRect(0, 0, 400, 200);
s.graphics.endFill();
s.scrollRect = new openfl.geom.Rectangle(0, 0, 200, 200);
```
On flash, a red **square** is displayed, but on openfl next targets, a red **rectangle** is displayed. It appears that scrollRect on openfl next doesn't clip any thing drawn via the graphics object.

**Comment by drezabek94** [comment]
Here is another instance of graphics command rendering incorrectly when paired with a scrollRect:
```
var s = new Sprite();
s.graphics.beginBitmapFill(openfl.Assets.getBitmapData("img/test.png"));
s.graphics.drawRect(0, 0, 300, 111);
s.graphics.endFill();
s.scrollRect = new openfl.geom.Rectangle(-50, -25, 400, 400);
```
On flash, assigning negative coordinates to the scrollRect has the effect of shifting the image over, as expected.
![good](https://cloud.githubusercontent.com/assets/1746884/6544026/c2e449f0-c4ff-11e4-9480-ae2bd0d7d175.png)
However, on openfl next targets, the image is not shifted, but it is clipped on the top and left edges. It looks like the bitmap fill is rendering from sprite origin (0,0) instead of scrollRect (50,25).
![bad](https://cloud.githubusercontent.com/assets/1746884/6544028/cb41a5de-c4ff-11e4-91ab-e919344b2e95.png)
I'm pretty sure this also occurs if the scrollRect position is positive, I chose negative so it is easier to notice.

**Comment by jgranick** [comment]
scrollRect should be vastly improved in current builds, thanks :smile:
