### ISSUE TITLE
Stage3D shouldn't use the same OpenGL context as OpenFL's rendrer

### ISSUE THREAD

**Issue by vroad** [openfl/openfl#532]
SInce they share the same OpenGL context, they may end up modifying rendering states in unexpected way.
It was so difficult for me to know that OpenFL was modifying colorMask.

**Comment by jgranick** [comment]
If we use the same context, I want to eventually track the changes made in order to keep things in a consistent state between the core renderer and Stage3D calls

I'm wondering, though, if we need a separate context, or framebuffer, in order to properly emulate the Stage3D APIs... or we need to queue the calls and run them only on present. Open to ideas

**Comment by vroad** [comment]
Probably we need to handle this in single context because on Android, I couldn't use multiple contexts with single SDL surface.

Would it be better to call OpenGL functions from wrapper classes that can save/restore render states, rather than calling them directly from Context3D? For now Context3D is calling GL APIs directly.

I'm also wondering if I should change render states right before issuing draw calls to minimize redundant state changes. I think we cannot use glGet here to get current render states because it's expensive.

**Comment by jgranick** [comment]
https://trello.com/c/G0tPxKGM/21-deepen-the-relationship-between-the-openfl-renderer-and-stage3d-resolve-change-of-state-conflicts
