### ISSUE TITLE
Embedded bitmaps on HTML5 should be preloaded

### ISSUE THREAD

**Issue by RealyUniqueName** [openfl/openfl#546]
If bitmap is embedded with `:bitmap` metadata, then it's loaded in runtime using this method: https://github.com/openfl/openfl/blob/master/openfl/display/BitmapData.hx#L1586
But this method loads bitmapdata asynchronously. 
So following code silently fails:

``` haxe
@:bitmap('mybitmap.png') class MyBitmap extends BitmapData { }

var bmp = new MyBitmap(0, 0);
graphics.beginBitmapFill(bmp);
//this line breaks execution because at this point bmp.width & bmp.height is still not set
graphics.drawRect(0, 0, bmp.width,  bmp.height);
graphics.endFill();
```

Since there is no way to load images synchronously in javascript, i think they should be preloaded during standart assets preloading.

**Comment by jgranick** [comment]
This is a tricky one.

You should be able to pass an "onload" handler in the constructor in order to receive when it is ready. If you want multiple instances of the same data, you need to be able to instantiate yourself. Also, for performance reasons, it may be preferable not to make them all instantiate at the beginning.

Maybe you're right. I think that @:bitmap is designed to cache the result the first time it is loaded. Perhaps all we need, then, is to instantiate each one with a load handler as part of the preload process

**Comment by RealyUniqueName** [comment]
With previous versions of OpenFL (i think prior to 2.x) it was loaded synchronously. I was able to execute that code without errors.  Also on other targets bitmap data is immediately available right after instantiation. 
So, i think, to make `:bitmap` consistent across all targets, preloading it during app start is the only way.

**Comment by jgranick** [comment]
I'm going to mark this as WONTFIX for now, if anyone is interested in coming up with a solution to make these preload on HTML5, would be open to taking a look, but otherwise I would not recommend embedded image assets on HTML5
