### ISSUE TITLE
Display list property access changes

### ISSUE THREAD

**Issue by ubald** [openfl/openfl#552]
A lot of properties from the display list are not (get,set) anymore. I use a port of Flex Framework for my layout and almost every property getter/setters needs to be overridden for it to work. 

Is there any good reason I don't understand for that choice?

**Comment by jgranick** [comment]
I would guess that using properties instead of getter/setters performs better, but if you need to override, I think in Haxe we really need to make them getter/setters in order to allow an override.

I'm concerned that we might have to do this for every property ever used -- it never ends, but perhaps the display list objects are good start

**Comment by ubald** [comment]
If the goal is still to mirror the flash api, I think the display list should all be made overridable since it works like this in Flash with all properties having getters/setters. And there is not a lot missing if I look at the source code.

**Comment by ibilon** [comment]
Any example of property that is causing issue?
