### ISSUE TITLE
[HTML5] @:bitmap BitmapData instances have width / height of 0

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#682]
``` haxe
package;

import openfl.display.BitmapData;
import openfl.display.Sprite;

@:bitmap("assets/openfl.png")
class Logo extends BitmapData {}

class Main extends Sprite {

    public function new () {
        super();
        var logo = new Logo(0, 0);
        trace(logo.width, logo.height);
    }
}
```

This outputs `512,200` on all targets as expected except for HTML5 where it's `0,0`.
The issue is present in legacy _and_ next.

Tested with Haxe 3.2.0, OpenFL 3.0.6 and Lime 2.4.1.

**Comment by azrafe7** [comment]
It happens because for html5 the image loading is done asynchronously. 

Openfl provides an onload callback you can pass to the `BitmapData` constructor, so this should run fine:

```haxe
    var logo = new Logo(0, 0, function(bmd) {
        trace(bmd.width, bmd.height);
    });
```
...but probably not what you want.

The _ugly & evil_ alternative is to change [`lime.graphics.Image.__fromBase64()`](https://github.com/openfl/lime/blob/6d58619294394846caebcba40a611281d36364bf/lime/graphics/Image.hx#L889-L912) to:

```haxe
	#if (js && html5)
	var image = new JSImage ();
	
	image.src = "data:" + type + ";base64," + base64;
	
	buffer = new ImageBuffer (null, image.width, image.height);
	buffer.__srcImage = cast image;
	
	offsetX = 0;
	offsetY = 0;
	width = buffer.width;
	height = buffer.height;
	
	if (onload != null) {
		
		onload (this);
		
	}
	
	#end
```

as described here http://stackoverflow.com/questions/9421202/how-do-i-make-an-image-load-synchronously (but not recommended and not even granted to be working synchronously on all browsers).

**Comment by Gama11** [comment]
How does OpenFL deal with this when it comes to regular `<assets>`?

**Comment by azrafe7** [comment]
The problem is inherent to the html5 spec in general, which is designed to load resources asynchronously and fire onload/onerror/etc events.

The other targets simply don't have this constraint, but that can make for an asymmetric API at times.

Hope I got this right, but probably @jgranick can offer some more inshights.

**Comment by larsiusprime** [comment]
There is a possible work-around for this issue, but it requires adding an
additional feature I've wanted for a while. On export, have the tools
inspect all the bitmapdata objects and write that data out, so that we can
have an additional Assets.getSize() command that gives you the width/height
of a bitmapdata without actually loading it.

This could partially solve our issue here -- we could instantiate a
temporary bitmapdata object of the correct size while it's loading and just
make it transparent, and let the coder use proper width/height right away.

On Mon, May 25, 2015 at 10:34 AM, Giuseppe Di Mauro <
notifications@github.com> wrote:

> The problem is inherent to the html5 spec in general, which is designed to
> load resources asynchronously and fire onload/onerror/etc events.
>
> The other targets simply don't have this constraint, but that can make for
> an asymmetric API at times.
>
> Hope I got this right, but probably @jgranick
> <https://github.com/jgranick> can offer some more inshights.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/issues/682#issuecomment-105252866>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jgranick** [comment]
Another workaround:

We presume that every embedded bitmap is going to be preloaded at the start of a project. Depending on how many you have, I'm not sure what the performance would be like, but this would make it instantiate in memory and keep it until you create a copy. This would make it fully synchronous.

The current solution works alright unless you need the 1.) size or 2.) bitmapData pixels/draw right away. The above would solve this (but is sort of messy)

**Comment by jgranick** [comment]
Related to: https://github.com/openfl/openfl/issues/546
