### ISSUE TITLE
Various Away3D/OpenGL related issues on native.

### ISSUE THREAD

**Issue by mauvecow** [openfl/openfl#708]
I've been trying to get Away3D working correctly under OpenFL3, and I've pretty much found all the bugs but not sure how the team would best want them to be fixed.
- Anisotropy is currently not detected because GL.getExtension() is not written for native targets.
- The enabling of Cairo text rendering by default in 3.1.0 causes a crash, because _internal/renderer/opengl/utils/SpriteBatch.hx: flush() does not rebind the buffers due to it still thinking that the same vertex buffer is bound, even though calls to various Context3D functions have unbound it.

Should a flag be raised when Context3D binds/unbinds a buffer?
- Display/BitmapData.hx: __drawGL() can be run in a state where face culling is enabled, and will be unable to draw to the screen if so.

Disable temporarily for this interval, or in the batcher, or somewhere else?
- _internal/renderer/opengl/utils/FilterTexture.hx: clear() does not clear the depth buffer, leaving garbage data on native.

Should this be cleared? Or if that isn't used, should depth reading/writing be disabled for this interval? (as called from BitmapData.__drawGL)

With the above issues resolved in some way, all of the Away3d examples run correctly.

**Comment by vroad** [comment]
I know many issues (and solutions) related to Stage3D wrapper implementation. I write here rather than creating new issue with similar name. These are not only for native, and at least one of your issue seems to apply for all targets except Flash( = native and html5).

I have fixed most of these problems by myself, and now I think that I should start sending pull requests.. 

- Render target texture is not supported
- Scissor rect is not correctly handled when you use ```clear()``` and ```setRenderToTexture() ```
- Render target texture gets y-flipped(upside down).
 - Solution: Y-flip all textures uploaded to GPU and flip them again in pixel shader. On WebGL you can do this with ```UNPACK_FLIP_Y_WEBGL```.
- Texture uploading is not optimized on js
 - Solution: Obtain byteView from ByteArrays to upload them directly
- We may should disable alpha-blending of WebGL canvas by default
- Shader variable locations are not cached
- Context3D generates mip maps every time textures are bound
 - Solution: Add a flag that indicates if mip maps are already generated
- Some rendering state settings are wrong
- There are many pieces of OpenGL code which don't seem to have meaning
- Texture filtering settings set with AGAL shader is not respected

My implementation supports things not supported in original Stage3D implementation. this may not be merged.
 - Alpha-only texture
 - Uploading from typed arrays to Vertex/Index buffers for better performance on js

I'm trying to avoid render state conflict issue by using custom renderer that doesn't do 2D rendering...
Text rendering is done on starling-openfl's QuadBatch API.

**Comment by vroad** [comment]
https://github.com/openfl/openfl/pull/721

**Comment by Greg209** [comment]
Just came across this thread and likewise I also have been looking at fixing (at least some of) the issues mentioned above to get OpenFL3 + Away3D to play nicely. @vroad , some of your solutions seem more comprehensive than what I have so I could either start creating my own PR's which would mean refactoring your code or if your in a position to start making PR's that would be great.

I think getting these fixes in as soon as possible would be great.

**Comment by vroad** [comment]
I'd like to send other pull requests, but my previous request is still not accepted.
https://github.com/openfl/openfl/pull/821

**Comment by vroad** [comment]
I recently found memory leak issue and created PR for that: https://github.com/openfl/openfl/pull/842

**Comment by vroad** [comment]
#721 was Fix MIPNONE to use nearest when filter is NEAREST

I've created other PR then.
Set precision only on OpenGL ES #879 (Merged)
Cache GLUniformLocation from AGAL shader (originally written by Haxiomic) #880

**Comment by mauvecow** [comment]
Looking good! Thankful someone else is on this too.

**Comment by vroad** [comment]
Add Context3DBufferUsage support #929

**Comment by vroad** [comment]
#936 is merged. Starling should run on HTML5 with this fix. As ByteArray impl has changed a lot in recent commits, I have to fix every piece of code using Std.is and cast with ByteArray, though.

**Comment by jgranick** [comment]
Away3D has been supported much better for a while. I am closing this issue since I am sure that many of these issues are resolved, but if there are any continuing problems, we can open new more specific issues :smile:
