### ISSUE TITLE
Missing classes in backends cause a class mix of chosen and default backend.

### ISSUE THREAD

**Issue by YellowAfterlife** [openfl/openfl#824]
It appears that when a custom backend is used, it's classes are included _over_ rather than _instead_ of default backend's. Thus, if you reference a class that is not present in the custom backend, you get a broken mix of code from both.
Example:
application.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<project>
	<meta title="TestOFL" package="cc.yal.TestOFL" version="1.0.0" company="YellowAfterlife" />
	<app main="Main" file="TestOFL" path="bin" swf-version="11.8" />
	<source path="src" />
	<set name="html5-backend" value="openfl-bitfive" />
	<haxelib name="openfl" />
</project>
```
src/Main.hx:
```haxe
import openfl.display.Application;
class Main {
	static function main() {
		
	}
}
```
log:
```
cmd: "C:\Dev\NME\haxe/haxelib" run lime build "application.xml" html5 -debug -Dfdb
.../haxe/lib/lime/2,6,1/lime/system/System.hx:111: characters 2-24 : Class<ApplicationMain> has no field create
.../haxe/lib/lime/2,6,1/lime/Assets.hx:498: characters 31-57 : DefaultAssetLibrary should be lime.AssetLibrary
.../haxe/lib/lime/2,6,1/lime/Assets.hx:498: characters 31-57 : For function argument 'library'
.../haxe/lib/openfl/3,3,2/openfl/display/Application.hx:16: characters 6-21 : Class<openfl.Lib> has no field application
.../haxe/lib/openfl/3,3,2/openfl/display/Application.hx:18: characters 3-18 : Class<openfl.Lib> has no field application
.../haxe/lib/openfl/3,3,2/openfl/display/Window.hx:28: characters 10-98 : Too many arguments
.../haxe/lib/openfl/3,3,2/openfl/display/Window.hx:28: characters 10-98 : Function 'new' requires no arguments
.../haxe/lib/openfl/3,3,2/openfl/display/Window.hx:29: characters 25-30 : openfl.display.Stage should be lime.app.IModule
.../haxe/lib/openfl/3,3,2/openfl/display/Window.hx:29: characters 25-30 : For function argument 'module'
bin/html5/haxe/ApplicationMain.hx:241: characters 2-9 : Main does not have a constructor
```

**Comment by jgranick** [comment]
Do you think it would work to add empty files that match the ones that aren't implemented? This way the compiler would say the classes are not defined, instead of breaking your build

**Comment by YellowAfterlife** [comment]
If I'm not mistaken, this did not occur until recently, as the missing classes did correctly "error" when I was expanding my implementation last time.
I definitely can add blank files but that does not seem like a good long-term solution as it leaves otherwise perfectly forward-compatible versions of the backend vulnerable to any new additions to the main class set.
The fact that certain files (e.g. templates) are being re-written 2+ times (e.g. index.html is being written by lime, then rewritten by openfl, then rewritten by bitfive) doesn't seem like a good thing for compile times either.

**Comment by jgranick** [comment]
In the first version of OpenFL, we used separate haxelibs, and imported based on the backend in use. Switching backends, at that point, shared none of the backend files, only some common files, such as `openfl.Assets`

In OpenFL 2 things were combined into one library, but the backends were still blocked from the code path. While compiling, class paths were added based on the backend used. This was similar to the first approach, but it worked without multiple haxelibs. However, `-lib openfl` wouldn't ever work in this sense since standard Haxe tools didn't find the backend classes.

OpenFL 3 does expose itself to the standard Haxe class path, but typedefs based on "openfl_legacy" if needed, on the native target. Also, OpenFL 3 relies upon Lime 2 in order to work, it is not as self-contained in that sense.

If you allow Lime 2 to be in the class path, then you might have less problems. If you override templates, you should be able to be sure that things work the way you want, and not to have some implicit Lime functionality going on.

Copying multiple template files is just done by convention in the tools, I'm sure this would be a simple fix in the PathHelper class (I think it is) if you want to optimize it, I wouldn't imagine this to have a noticeable performance improvement, though.

**Comment by YellowAfterlife** [comment]
I'm already overriding the templates, but, as the example shows, inclusion of Lime' classes results in it's unmatched expectations for those exact templates I've overriden. Which is the reason why I've started overriding more templates in first place - it is no fun to have the code break whenever something somewhere was altered and you didn't notice due to other workload.

**Comment by jgranick** [comment]
Oh, I see now, so you do override, but the version of those files you are not using don't process properly, and cause the whole thing to break. Makes sense. I bet making it accumulate matches (instead of copying) and then copy only the final match would fix this

**Comment by YellowAfterlife** [comment]
Was this actually fixed or anything?

**Comment by ibilon** [comment]
Not fixed, the entire openfl package is in the class path, so not much possible here.
I don't even think there's still a concept of backend in openfl anymore since all is based on lime.

Re-reading the issue I seemed to have miss some information about templates but seems to be an optimization on the tools which I already plan on profiling/improving.
