### ISSUE TITLE
Html5 black screen issue for openfl > 3.3.4

### ISSUE THREAD

**Issue by iskolbin** [openfl/openfl#875]
Hi, recently i updated openfl to newest version and encountered this issue. Building html5 with openfl > 3.3.4 results with black screen on some weak devices (tested on 100$ tablets with Android 4.2, Samsung Duos and Zotac minibox with 4Gb ram and nvidia 520 gt). Searching through commits I found this one:

https://github.com/openfl/openfl/commit/fd9a1156c4c1040ff7b3d8484edeca99f95b8074

``` diff
        #if (js && html5)

-       var directRender = (graphics.__hardware && renderSession.context != null);
+       // TODO: Handle world transform if we want to use direct render
+       
+       //var directRender = (graphics.__hardware && renderSession.context != null);
+       var directRender = false;

        if (graphics.__dirty || directRender) {
```

After recommenting directRender assignment everything works fine (openfl 3.3.8, lime 2.6.8).

**Comment by mauvecow** [comment]
For the record, I was able to reproduce this myself, and reverting it did cause it to work.

Appears to be a bounds clipping issue of some sort. I could see the upper left portion of the screen, and more would open as I drew objects further down and to the right. This only occured because I was upscaling my tiles to double size, which apparently upscaled the bounds too; resetting that to 1x just gave me a black screen.
