### ISSUE TITLE
Preloader loading always OGG instead any other sound-format (e.g. MP3)

### ISSUE THREAD

**Issue by fzzr-** [openfl/openfl#940]
[HERE: openfl.display.Preloader.hx 77:58/3](https://github.com/openfl/openfl/blob/master/openfl/display/Preloader.hx#L77)

**Target: JS/HTML5**

In assets I have:
- sound.mp3
- sound.ogg

For all browser (desktops & mobile including iOS) `openfl.display.Preloader` loading always `sound.ogg` instead `sound.mp3`.
1. `OGG` needed only for Chromium-based & Ardoid-browsers;
2. `MP3` fully supported anywhere excluding `1.`.

See [MDN:: Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility).

---

> One founded [solution: html5hub.com/...](http://html5hub.com/so-do-we-have-a-cross-browser-audio-format-yet/).
> 
> ``` js
> var fileFormat = "mp3";
> var mp3Test = new Audio();
> var canPlayMP3 = (typeof mp3Test.canPlayType === "function" && mp3Test.canPlayType("audio/mpeg") !== "");
> if (!canPlayMP3) {
>     fileFormat = "ogg";
> }
> ```

**Comment by jgranick** [comment]
Sound.js will pick the format it wants by default. Unfortunately, if one is missing, it fails to skip and move on to trying another compatible format.

We use OGG as the first default setting since that's what desktop and mobile projects usually use first. If not supported by the browser, it goes on to the next format.

Even though we use ".ogg" it still switches if not supported

**Comment by loudoweb** [comment]
> Even though we use ".ogg" it still switches if not supported

I have encountered a problem when it doesn't switch. Server send 404 error because they forbid the related mime type of .ogg (but the file is in the server). So it's a very special case that occured because of some bad configured server (and that's the client server not mine, so I can't fix the mime type). Is there a way to force mp3 on my app?

**Comment by ibilon** [comment]
Maybe if you changed https://github.com/openfl/openfl/blob/50fc31603d2dbe42413b80e472e0ecbd5c892cd9/openfl/media/Sound.hx#L203 to put mp3 in first.

If that helps we could add a configuration value for this.

**Comment by loudoweb** [comment]
Thanks for your reply. Doesn't seem to work. That's strange because even 
`SoundJS.alternateExtensions = [  "mp3" ];`
tries to load ogg files.

**Comment by loudoweb** [comment]
I did it!

No need to change Sound.hx. If we want to have the ability to prioritize mp3 or ogg, we need to configure here : 

https://github.com/openfl/openfl/blob/50fc31603d2dbe42413b80e472e0ecbd5c892cd9/openfl/display/Preloader.hx#L77
