### ISSUE TITLE
Custom shaders broke with Lime 2.8.0

### ISSUE THREAD

**Issue by er453r** [openfl/openfl#960]
They still work with lime 2.7.0, regardless of the openfl version.

**Comment by larsiusprime** [comment]
Two questions:

1. What target/platform were you using? Win/Mac/Linux, cpp, html5, ios, android, etc?
2. Are they also broken in 2.8.1 ?

**Comment by er453r** [comment]
Ooops, sorry for no including this basic info - it is really late in my time zone...

1. I'm testing only on HTML5 target with `-Dwebgl` 
2. They are still broken in 2.8.1

**Comment by larsiusprime** [comment]
Are they broken in all browsers, or just a specific one?

**Comment by er453r** [comment]
Tested in newest Chrome & Firefox - both do not work

**Comment by larsiusprime** [comment]
Do you know if shaders work in neko / cpp target for you?

**Comment by er453r** [comment]
Unfortunately I'm unable to test it now - my project in wildly html5 specific. I will try to prepare a minimal test case tomorrow and test it on other targets.

**Comment by er453r** [comment]
Here is a minimal test case that works on Lime 2.7.0 and OpenFL 3.4.0 - working with neko and html5 webgl renderer. Shaders stop working with any newer version .

	package;

	import openfl.filters.ColorMatrixFilter;
	import openfl.display.Sprite;

	class Main extends Sprite {
		private static var negativeFilter:ColorMatrixFilter = new ColorMatrixFilter([
			-1,  0,  0, 0, 255,
			 0, -1,  0, 0, 255,
			 0,  0, -1, 0, 255,
			 0,  0,  0, 1,   0
		]);

		public function new() {
			super();
		
			var square = new Sprite();
			square.graphics.beginFill(0xff0000);
			square.graphics.drawRect(0, 0, 100, 100);
			addChild(square);

			this.filters = [negativeFilter];
		}		
	}

**Comment by er453r** [comment]
Guys, I've been trying to fix this for some time now with no results - the issue seems to be in lime, not in openfl. Could some one point me in the right direction (files/methods) to look into?

**Comment by juakob** [comment]
I found the same bug, but I think the title is a little miss leading. I found that openfl is not drawing when you use cacheAsBitmap or a filter. If you just use sprite.shader or  sprite.graphics.drawTiles you dont have any problem. In set_filters in DisplayObject you can see that when you apply a filter the  __cacheAsBitmap is turn on. So the bug is just in cacheAsBitmap. I think it must be something with the size/position of the render target or something with the switch, didn't have time to found what is happening. Here you can test more [examples ](https://github.com/mrcdk/openfl-samples/tree/94f92ccf7a4a905985c95e05de80f7375899131a)
Pleas test them and if you found the same result update the title of the issue to reflect that just cacheAsBitmap is not working. 
I found [this](https://github.com/openfl/openfl/pull/874), so there are some "bugs" with cacheAsBitmap

**Comment by er453r** [comment]
Thanks for your input! It pointed me in the right direction. Turns out I was wrong. I was testing wrong. It is not the shaders that have this problem, it was `ColorMatrixFilter` I've used for testing all along...

I'm closing this issue, and creating a new one here https://github.com/openfl/openfl/issues/1049
