### ISSUE TITLE
Version 3.5.2 does not play nice with the air3 haxelib. Forces use of openfl flash externs

### ISSUE THREAD

**Issue by Mechameesh** [openfl/openfl#971]
I might be wrong about this, but it seems to me that the openfl.Lib.includeExterns() macro makes sure that the externs for the flash platform are the openFL since they are added as the final codepath for those namespaces. 

Since the extern/flash/\* externs do not contain the AIR only externs, builds that previously worked with the [air3 haxelib](http://lib.haxe.org/p/air3/) now fail.

Would it be possible to include the AIR externs possibly with a `@:require(flash_air)`? If need be i'll do it as a pull request

**Comment by jgranick** [comment]
Rather than relying upon the Haxe standard Flash extern types, we use our own types now to unify a number of small discrepancies between platforms (for example, `SharedObjectFlushStatus` should be an enum, not a string).

Perhaps there's a way we could merge AIR compatibility into our flash.* externs. The "air" package would still be needed, but this might fix any problems with the "flash" classes we define.

**Comment by Mechameesh** [comment]
So where do we go from here? I can do a pull request with the air externs over the course of a week or two...

**Comment by TomByrne** [comment]
I'd also be keen to find a clean solution to this.
Currently I just have to add fields to the openfl externs (in flash.*).

**Comment by jgranick** [comment]
I think we should use `#if air` (or similar) to add AIR-specific APIs in the externs, so it does not expose in normal use, but will be available for applications targeting Adobe AIR

**Comment by jgranick** [comment]
This is resolved in the newest release, with proper Adobe AIR support added to Lime :smile:
