### ISSUE TITLE
MovieClip dynamic use?

### ISSUE THREAD

**Issue by KnightMearh** [openfl/openfl#996]
Flash had a pretty handy way to access MovieClip children as properties, ie myClip.mySubClip.myImage. The compiler will not allow this syntax because it obviously doesn't have access to the clip's children during compilation.

But one easy way to achieve this is to set MovieClip to implement Dynamic.
class MovieClip extends Sprite implements Dynamic {

The code completion for type MovieClip still works, and it seems to even assume every .child is also a MovieClip (which most of the time is probably true).

However, I can see plenty of arguments for not having this feature. What do you think about it? Was it decided that it is just preferred to use myClip.getChildByName( "child" ) instead of myClip.child in OpenFL?

**Comment by jgranick** [comment]
For a long time (for performance) we did not support dynamic access at all. Using `myClip.getChildByName` would have been your only path to getting a named child (unless you already had a reference).

In recent releases (perhaps not on legacy, but in current OpenFL) we support Dynamic<DisplayObject> access. True `implements Dynamic` access would fall down when trying to access getters and setters of children, which are not "true" properties, but are functions which need to be called. Doing a `Dynamic` would remove the type data and cause errors on most platforms.

`implements Dynamic<DisplayObject>` means that you can use `myClip.mySubClip.myImage`, but if you access properties specific, say, to a `Bitmap`, you may need to cast it first (`cast (myClip.mySubClip.myImage, Bitmap).smoothing = true;`)

When using the SWF library, and using the "generate" option to create instances like `new MySymbol ();` rather than `Assets.getMovieClip`, it gives you types for the first level of objects, so if `myClip.myTextField` exists, it will be typed as a `TextField` and not as a generic `DisplayObject`, but if you delve deeper into a hierarchy, you'll lose the precision, and will need to cast if you need to access something implemented in a subclass.

Does this make sense? Have you tried it?

**Comment by KnightMearh** [comment]
Right, in flash you wouldn't get compiler warnings about <code>myClip.myChild</code> not existing (it would be null at runtime). But if you used a SWC (ie, embedding as you suggested with <code>new MyClass()</code>) it would run through the compiler.

I tried to use a swf with the 'generate' option before, but I think I couldn't get it working. In any case, my main use of swf down the road would be to load it at runtime so I likely won't have access to the class structures at compile-time anyway.

So, I am slightly confused... Are you affirming that openfl users should just solely use <code>getChildByName()</code> or are you mentioning that the Dynamic use of <code>MovieClip</code> currently exists in some way? Is it possible to have <code>MovieClip</code> be <code>Dynamic</code> for just Flash and HTML5 targets (or any others that could use it)? Overall it is nice shorthand functionality that saves a lot of typing, but it's not at all the end of the world to be forced into <code>getChildByName()</code>. Just wanted to be sure it wasn't a 'missing' or overlooked feature vs being decidedly not supported that way.

**Comment by ibilon** [comment]
I removed the `implements Dynamic` in 32780e256e595d83016253892043d56662cf6a90, too many issues.

So the need here is to access children of movie clips?
If it's at runtime then you'll need to use `getChildByName()`, I don't see how we could do it in a safe way otherwise.
But if the swf is known at runtime we could use a macro to fill the missing properties,
giving access while still keeping the type safety.

I'm not too familiar with the ways to use a swf with openfl yet, I'll look into it.

**Comment by jgranick** [comment]
Using the "generate" SWF option with currently OpenFL releases will export statically typed definitions for each exported type, removing the need for most dynamic access.

You can also use `-Dopenfl-dynamic` now to use `Dynamic` `MovieClip` and `Event` types. In other words, we use the behavior of `-Dflash-strict` by default, and this toggles it back to dynamic behavior :smile:

**Comment by mastef** [comment]
So as you mention, `implements Dynamic` doesn't call the `get`ters and `set`ters ( properties )

I'd propose to add a `implements DynamicProp` ( `-Dopenfl-dynamic-prop` ) which basically has on the `set` and `get` functions a `Reflect.getProperty` instead of `Reflect.field` and `Reflect.setProperty` instead of `Reflect.setField`

Also worth adding an exception if `Reflect.hasField()` turns out empty.

I did something similar here, calling it an abstract `MoviePlus`. Starts around line 81 https://try.haxe.org/#2119B

Would implements DynamicProp be a better solution? I guess it could allow access like `b.c` instead of the `@:arrayAccess` way of `b["c"]`

**Comment by mastef** [comment]
So I did the big wahoo now in 3 places about this since yesterday - why it's `extends DisplayObject` as it has imho the least benefits - it still doesn't allow you to access MovieClip methods/props without casting, just for the benefit to add TextFields - that doesn't seem like a too big benefit with a much bigger downside ( you still have to cast all children MovieClips )

Imho a MovieClip should have `extends MovieClip`, a DisplayObject could have `extends DisplayObject` etc.

Another way may be to have `openfl-dynamic` accept a variable, what it implements by default? Since this doesn't seem like a well documented feature anyway ( googling for `openfl_dynamic` brings us here, and googling for `openfl-dynamic` brings us to the [initial thread where this was implemented in](http://community.openfl.org/t/clearer-errors-to-help-debugging/8362/9) )

Something like `<haxeflag name="-Dopenfl-dynamic" value="MovieClip" />` that defaults to `DisplayObject` could be a compromise?
