### ISSUE TITLE
[NEXT] stage.displayState ignoring alt+enter

### ISSUE THREAD

**Issue by SARFEX** [openfl/openfl#997]
Subj,
Alt+Enter toggling fullscreen mode and the window size changes, but displayState variable stays same.
Thank you.

Target: windows/neko next
On legacy all good. 

OpenFL 3.5.3
Lime 2.8.2
Haxe 3.2.1

**UPD:** on previous versions OpenFL 3.5.2 and Lime 2.8.1 all work correct also

**Comment by SARFEX** [comment]
ok, i found Lib.current.stage.window.fullscreen

**Comment by SARFEX** [comment]
I made little tests about this issue here https://github.com/HaxeFlixel/flixel/pull/1684#issuecomment-170165205

**Comment by jgranick** [comment]
I have not had a chance to try yet, but I think this commit should fix it. If you do not mind making this little change on your copy, I'd love to hear if it works as you expect. Thank you! :smile:

**Comment by SARFEX** [comment]
Thank you for commit. It works only half, for some reason onWindowRestore is not calling or override. __displayState retains previous value (FULL_SCREEN_INTERACTIVE)

**Comment by jgranick** [comment]
Okay, I think I have it :smile:

At first, we did not change the `displayState` based on Lime events, because OpenFL was in charge of deciding when to go fullscreen and not, but it made more sense to push the Alt+Enter (and other standard) behavior into Lime instead. Now, Lime was changing (and is changing) the display state, and OpenFL needs to detect and respond to this properly.

I made a mistake when I used `onWindowRestore`, I forgot this occurs only when _restoring_ a window from being minimized.

In lieu of another event (not sure if we should add one?) I'm doing it now in `onWindowResize` and check if `displayState` is `NORMAL` and if `!window.fullscreen`

This seems to be working properly now. Thanks again for bringing this up!
